In [1]:
import pandas as pd
from sklearn.decomposition import PCA
from pybaseball import cache, statcast_batter, playerid_lookup

In [3]:
playerid_lookup('Guerrero', 'Vladimir')

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,guerrero,vladimir,665489,guerv002,guerrvl02,19611,2019.0,2025.0
1,guerrero,vladimir,115223,guerv001,guerrvl01,778,1996.0,2011.0

In [5]:
df = statcast_batter('2025-09-29', '2025-11-01', player_id = 665489)
df = df.to_csv("/Users/lucasben/Documents/mba-business-analytics/courses/predictive-modelling/vlad_playoffs.csv")

Gathering Player Data

In [9]:
df = pd.read_csv("/Users/lucasben/Documents/mba-business-analytics/courses/predictive-modelling/vlad_playoffs.csv")
df.head()

,Unnamed: 0,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,0,FS,2025-11-01,87.5,-1.64,6.08,"Guerrero Jr., Vladimir",665489,660271,NaN,...,NaN,2.65,0.72,0.72,46.4,NaN,NaN,NaN,NaN,NaN
1,1,SI,2025-11-01,97.0,-1.45,5.94,"Guerrero Jr., Vladimir",665489,607192,field_out,...,NaN,1.36,1.27,1.27,53.9,-5.895606,5.569962,32.047206,32.838527,26.645300
2,2,SL,2025-11-01,88.9,-1.44,5.97,"Guerrero Jr., Vladimir",665489,607192,NaN,...,NaN,3.23,-0.07,-0.07,55.4,NaN,NaN,NaN,NaN,NaN
3,3,FF,2025-11-01,96.9,-2.01,5.25,"Guerrero Jr., Vladimir",665489,808967,double,...,NaN,0.90,0.61,0.61,38.9,7.529483,-14.931355,30.969012,24.214118,30.655963
4,4,FS,2025-11-01,91.3,-2.04,5.18,"Guerrero Jr., Vladimir",665489,808967,NaN,...,NaN,2.79,0.70,0.70,38.2,NaN,NaN,NaN,NaN,NaN