In [40]:
import pandas as pd
from sklearn.decomposition import PCA
from pybaseball import cache, statcast_batter, playerid_lookup
import numpy as np
from numpy import linalg

In [3]:
playerid_lookup('Guerrero', 'Vladimir')

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,guerrero,vladimir,665489,guerv002,guerrvl02,19611,2019.0,2025.0
1,guerrero,vladimir,115223,guerv001,guerrvl01,778,1996.0,2011.0

In [5]:
df = statcast_batter('2025-09-29', '2025-11-01', player_id = 665489)
df = df.to_csv("/Users/lucasben/Documents/mba-business-analytics/courses/predictive-modelling/vlad_playoffs.csv")

Gathering Player Data

In [9]:
df = pd.read_csv("/Users/lucasben/Documents/mba-business-analytics/courses/predictive-modelling/vlad_playoffs.csv")
df.head()

,Unnamed: 0,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,0,FS,2025-11-01,87.5,-1.64,6.08,"Guerrero Jr., Vladimir",665489,660271,NaN,...,NaN,2.65,0.72,0.72,46.4,NaN,NaN,NaN,NaN,NaN
1,1,SI,2025-11-01,97.0,-1.45,5.94,"Guerrero Jr., Vladimir",665489,607192,field_out,...,NaN,1.36,1.27,1.27,53.9,-5.895606,5.569962,32.047206,32.838527,26.645300
2,2,SL,2025-11-01,88.9,-1.44,5.97,"Guerrero Jr., Vladimir",665489,607192,NaN,...,NaN,3.23,-0.07,-0.07,55.4,NaN,NaN,NaN,NaN,NaN
3,3,FF,2025-11-01,96.9,-2.01,5.25,"Guerrero Jr., Vladimir",665489,808967,double,...,NaN,0.90,0.61,0.61,38.9,7.529483,-14.931355,30.969012,24.214118,30.655963
4,4,FS,2025-11-01,91.3,-2.04,5.18,"Guerrero Jr., Vladimir",665489,808967,NaN,...,NaN,2.79,0.70,0.70,38.2,NaN,NaN,NaN,NaN,NaN

In [20]:
df["game_date"].value_counts().sort_index()

game_date
2025-10-04    22
2025-10-05    15
2025-10-07    18
2025-10-08    24
2025-10-12    15
2025-10-13    23
2025-10-15     8
2025-10-16    12
2025-10-17     7
2025-10-19    12
2025-10-20    14
2025-10-24    21
2025-10-25    19
2025-10-27    35
2025-10-28    13
2025-10-29    20
2025-10-31    17
2025-11-01    24
Name: count, dtype: int64

In [21]:
list(df.dtypes)

[dtype('int64'),
 dtype('O'),
 dtype('O'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('O'),
 dtype('int64'),
 dtype('int64'),
 dtype('O'),
 dtype('O'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('O'),
 dtype('float64'),
 dtype('O'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('O'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('O'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('O'),
 dtype('O'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64')]

In [26]:
df.isna().sum()[df.isna().sum() > 0]

events                                      236
spin_dir                                    319
spin_rate_deprecated                        319
break_angle_deprecated                      319
break_length_deprecated                     319
hit_location                                253
bb_type                                     252
on_3b                                       283
on_2b                                       286
on_1b                                       194
hc_x                                        252
hc_y                                        252
tfs_deprecated                              319
tfs_zulu_deprecated                         319
umpire                                      319
sv_id                                       319
hit_distance_sc                             214
launch_speed                                215
launch_angle                                214
estimated_ba_using_speedangle               253
estimated_woba_using_speedangle             237
woba_value                                  236
woba_denom                                  237
babip_value                                 236
iso_value                                   236
launch_speed_angle                          253
bat_speed                                   183
swing_length                                183
estimated_slg_using_speedangle              253
hyper_speed                                 214
pitcher_days_until_next_game                141
batter_days_until_next_game                  24
attack_angle                                183
attack_direction                            183
swing_path_tilt                             183
intercept_ball_minus_batter_pos_x_inches    183
intercept_ball_minus_batter_pos_y_inches    183
dtype: int64

In [27]:
df.shape

(319, 119)

In [29]:
percentage_missing = (df.isna().sum() / len(df)) * 100
list(percentage_missing)

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 73.98119122257053,
 0.0,
 100.0,
 100.0,
 100.0,
 100.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 79.3103448275862,
 78.99686520376176,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 88.71473354231975,
 89.65517241379311,
 60.81504702194357,
 0.0,
 0.0,
 0.0,
 78.99686520376176,
 78.99686520376176,
 100.0,
 100.0,
 100.0,
 100.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 67.0846394984326,
 67.39811912225704,
 67.0846394984326,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 79.3103448275862,
 74.29467084639498,
 73.98119122257053,
 74.29467084639498,
 73.98119122257053,
 73.98119122257053,
 79.3103448275862,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 57.36677115987461,
 57.36677115987461,
 79.3103448275862,
 0.0,
 67.0846394984326,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 44.20062695924764,
 7.523510971786834,
 0.0,
 0.0,
 0.0,
 0.0,
 57.36677115987461,
 57.36677115987461,
 57.36677115987461,
 57.36677115987461,
 57.36677115987461]

In [39]:
no_missing_cols = df.columns[df.isna().sum() == 0]
len(no_missing_cols)

82

In [ ]:
matrix = df[no_missing_cols]

(319, 82)

In [ ]:
num_matrix = matrix.select_dtypes(include=['number'])

svd_matrix = np.linalg.svd(num_matrix) # singular value decomposition

In [ ]:
V_transpose = svd_matrix[2] # getting the right singular vectors
V = V_transpose.T
V

array([[-7.38702878e-05, -7.17958197e-04,  1.60409404e-04, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-4.22939302e-05,  4.85064094e-06,  8.96608413e-06, ...,
         6.43528199e-16, -1.50975153e-15,  1.47905505e-16],
       [ 6.38580440e-07, -1.15647369e-06,  3.74827055e-06, ...,
         4.56047177e-16,  5.64440081e-16,  6.02039635e-18],
       ...,
       [-1.93890415e-07, -1.06198182e-06,  4.72021104e-08, ...,
         2.68448458e-16,  9.99092302e-17,  9.61111345e-17],
       [-1.49988918e-07, -4.19343929e-07, -7.45461965e-07, ...,
         1.13092375e-03, -3.50260453e-03,  1.62980037e-04],
       [-1.79636014e-05,  3.07900977e-05,  1.74783956e-05, ...,
         2.64274280e-17,  3.68628739e-17, -3.48299948e-18]])

In [76]:
pca = PCA()

pca.fit(num_matrix)

explained_variance = pca.explained_variance_ratio_

pca.components_

array([[ 7.87190748e-04,  6.94329754e-06, -5.28174674e-07, ...,
         1.24271610e-06,  8.49066627e-07, -3.87474848e-05],
       [-1.34256928e-04, -5.62999630e-06, -4.98841832e-06, ...,
         1.90124044e-08,  1.03090537e-06, -2.65188940e-05],
       [ 2.89861361e-04,  6.94681639e-06, -6.21326661e-06, ...,
         4.97863536e-07,  1.56076995e-06, -6.47373577e-05],
       ...,
       [ 0.00000000e+00, -4.23017184e-17, -1.52063771e-18, ...,
        -6.82445266e-17,  1.71323295e-15, -1.64315834e-17],
       [-0.00000000e+00,  8.18319180e-17, -4.92731580e-17, ...,
         2.60350250e-17, -2.18160225e-16, -4.04947032e-19],
       [-0.00000000e+00, -6.66619537e-12, -1.90205350e-12, ...,
        -1.91288652e-12,  1.18091794e-02, -1.74207870e-13]])

In [ ]:
sum(explained_variance[:4]) # 4 principal components explain 90% of the variation in the data

0.8934088828644907

In [69]:
explained_variance

array([3.84869704e-01, 2.20383266e-01, 1.83533905e-01, 1.04622008e-01,
       6.66382618e-02, 2.69384130e-02, 1.09635315e-02, 1.73474722e-03,
       3.06453005e-04, 9.41843160e-06, 2.07628363e-07, 3.96378850e-08,
       2.60463897e-08, 7.25652005e-09, 3.69858776e-09, 2.30035689e-09,
       1.09133301e-09, 8.99152674e-10, 7.82973465e-10, 6.15074632e-10,
       4.57119437e-10, 4.15757733e-10, 3.25767580e-10, 1.99841587e-10,
       1.78080849e-10, 1.63886913e-10, 1.40289750e-10, 1.26637222e-10,
       4.09401817e-11, 3.24267680e-11, 2.48402995e-11, 2.19822173e-11,
       2.09603655e-11, 1.61913192e-11, 9.45734457e-12, 5.43984737e-12,
       2.99869472e-12, 2.69835746e-12, 2.49115657e-12, 2.17866321e-12,
       1.84875226e-12, 1.30207938e-12, 7.80249920e-13, 6.14042189e-13,
       3.76044004e-13, 2.31876823e-13, 1.99765717e-13, 1.55389791e-13,
       1.19630114e-13, 1.14989163e-13, 7.38682988e-14, 5.06009924e-14,
       3.75698647e-14, 1.91570082e-14, 1.47367747e-14, 5.94245045e-15,
       2.47792887e-33, 2.47792887e-33, 2.47792887e-33, 2.47792887e-33,
       2.47792887e-33, 2.47792887e-33, 2.47792887e-33, 2.47792887e-33,
       2.47792887e-33, 2.47792887e-33, 2.47792887e-33])

In [81]:
# blue jays average ages
array = np.array([26, 26, 26, 27, 25, 26, 28,30, 35])
array.mean()

27.666666666666668

In [86]:
array = np.array([34, 36, 31, 30, 40, 29])
array.mean()

array2 =  np.array([34, 36, 31, 30, 40])
array2.mean()

34.2