In [1]:
import pandas as pd
import geopandas as gpd
import re
import numpy as np

In [2]:
neighbour_profiles = pd.read_excel('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/neighbourhood-profiles-2021-158-model.xlsx')
child_centres = gpd.read_file('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/EarlyON Child and Family Centres Locations - geometry - 4326.geojson')
improvement_areas = gpd.read_file('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/Neighbourhood Improvement Areas - 4326.geojson')

## **Neighbourhood Profiles Data**

In [3]:
neighbour_profiles
transpose = neighbour_profiles.set_index(neighbour_profiles.columns[0]).T # transpose data
transpose = transpose.reset_index().rename(columns={'index': 'Neighbourhood'}) # reset the index to make neighbourhood index
transpose

Neighbourhood Name,Neighbourhood,Neighbourhood Number,TSNS 2020 Designation,Total - Age groups of the population - 25% sample data,0 to 14 years,0 to 4 years,5 to 9 years,10 to 14 years,15 to 64 years,15 to 19 years,...,Between 9 a.m. and 11:59 a.m.,Between 12 p.m. and 4:59 a.m.,Total - Eligibility for instruction in the minority official language for the population in private households born in 2003 or later - 25% sample data,Children eligible for instruction in the minority official language,Children not eligible for instruction in the minority official language,"Total - Eligibility and instruction in the minority official language, for the population in private households born between 2003 and 2015 (inclusive) - 25% sample data",Children eligible for instruction in the minority official language,Eligible children who have been instructed in the minority official language at the primary or secondary level in Canada,Eligible children who have not been instructed in the minority official language at the primary or secondary level in Canada,Children not eligible for instruction in the minority official language
0,West Humber-Clairville,1,Not an NIA or Emerging Neighbourhood,33300,4295,1460,1345,1485,23640,1860,...,1665,2935,5430,410,5020,3875,335,255,75,3540
1,Mount Olive-Silverstone-Jamestown,2,Neighbourhood Improvement Area,31345,5690,1650,1860,2175,21490,2280,...,1145,2965,7285,510,6780,5540,395,245,145,5145
2,Thistletown-Beaumond Heights,3,Neighbourhood Improvement Area,9850,1495,505,540,455,6615,570,...,395,635,1860,180,1685,1325,120,75,45,1205
3,Rexdale-Kipling,4,Not an NIA or Emerging Neighbourhood,10375,1575,505,615,455,6950,515,...,425,775,1910,135,1770,1370,90,75,25,1275
4,Elms-Old Rexdale,5,Neighbourhood Improvement Area,9355,1610,440,480,685,6355,635,...,355,675,2015,95,1920,1520,70,60,10,1445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Yonge-Bay Corridor,170,Not an NIA or Emerging Neighbourhood,12645,970,500,270,200,10820,340,...,695,330,1075,50,1020,555,30,10,20,520
154,Junction-Wallace Emerson,171,Not an NIA or Emerging Neighbourhood,23180,3075,1135,1020,925,17200,750,...,1185,1105,3580,410,3170,2375,305,190,115,2075
155,Dovercourt Village,172,Not an NIA or Emerging Neighbourhood,12380,1365,445,430,490,9040,460,...,775,570,1665,175,1490,1190,130,95,35,1060
156,North Toronto,173,Not an NIA or Emerging Neighbourhood,15885,1315,535,390,390,12780,465,...,970,550,1620,145,1470,1050,95,65,30,955
157,South Eglinton-Davisville,174,Not an NIA or Emerging Neighbourhood,22735,2190,910,670,610,17495,575,...,1390,730,2570,265,2300,1580,155,105,45,1420

In [4]:
transpose.to_csv('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/neighbourhood_profiles_clean.csv', index=False)

In [5]:
list(transpose.columns)

['Neighbourhood',
 'Neighbourhood Number',
 'TSNS 2020 Designation',
 'Total - Age groups of the population - 25% sample data',
 '  0 to 14 years',
 '    0 to 4 years',
 '    5 to 9 years',
 '    10 to 14 years',
 '  15 to 64 years',
 '    15 to 19 years',
 '    20 to 24 years',
 '    25 to 29 years',
 '    30 to 34 years',
 '    35 to 39 years',
 '    40 to 44 years',
 '    45 to 49 years',
 '    50 to 54 years',
 '    55 to 59 years',
 '    60 to 64 years',
 '  65 years and over',
 '    65 to 69 years',
 '    70 to 74 years',
 '    75 to 79 years',
 '    80 to 84 years',
 '    85 years and over',
 '      85 to 89 years',
 '      90 to 94 years',
 '      95 to 99 years',
 '      100 years and over',
 'Total - Distribution (%) of the population by broad age groups - 25% sample data',
 '  0 to 14 years',
 '  15 to 64 years',
 '  65 years and over',
 '    85 years and over',
 'Average age of the population',
 'Median age of the population',
 'Total - Persons in private households - 25% sample data',
 '  Total - Persons in census families',
 '    Married spouses or common-law partners',
 '    Parents in one-parent families',
 '    Children',
 '      In a two-parent family',
 '      In a one-parent family',
 '  Total - Persons not in census families in private households - 25% sample data',
 '    Living alone',
 '    Living with other relatives',
 '    Living with non-relatives only',
 'Number of persons in private households',
 'Total - Marital status for the total population aged 15 years and over - 25% sample data',
 '  Married or living common-law',
 '    Married',
 '    Living common-law',
 '      Living common law - Never married',
 '      Living common law - Separated',
 '      Living common law - Divorced',
 '      Living common law - Widowed',
 '  Not married and not living common-law',
 '    Not married and not living common law - Never married',
 '    Not married and not living common law - Separated',
 '    Not married and not living common law - Divorced',
 '    Not married and not living common law - Widowed',
 'Total - Income statistics in 2020 for the population aged 15 years and over in private households - 25% sample data',
 '  Number of total income recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median total income in 2020  among recipients ($)',
 '    Average total income in 2020 among recipients ($)',
 '  Number of after-tax income recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median after-tax income in 2020 among recipients ($)',
 '    Average after-tax income in 2020 among recipients ($)',
 '  Number of market income recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median market income in 2020  among recipients ($)',
 '    Average market income in 2020 among recipients ($)',
 '  Number of employment income recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median employment income in 2020 among recipients ($)',
 '    Average employment income in 2020 among recipients ($)',
 '  Number of government transfers recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median government transfers in 2020 among recipients ($)',
 '    Average government transfers in 2020 among recipients ($)',
 '  Number of employment insurance benefits recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median employment insurance benefits in 2020 among recipients ($)',
 '    Average employment insurance benefits in 2020 among recipients ($)',
 '  Number of COVID-19 emergency and recovery benefits recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median COVID-19 emergency and recovery benefits in 2020 among recipients ($)',
 '    Average COVID-19 emergency and recovery benefits in 2020 among recipients ($)',
 'Composition of total income in 2020 of the population aged 15 years and over in private households (%) - 25% sample data',
 '  Market income (%)',
 '    Employment income (%)',
 '  Government transfers (%)',
 '    Employment insurance benefits (%)',
 '    COVID-19 - Government income support and benefits (%)',
 '      COVID-19 - Emergency and recovery benefits (%)',
 'Total - Total income groups in 2020 for the population aged 15 years and over in private households - 25% sample data',
 '  Without total income',
 '  With total income',
 '    Under $10,000 (including loss)',
 '    $10,000 to $19,999',
 '    $20,000 to $29,999',
 '    $30,000 to $39,999',
 '    $40,000 to $49,999',
 '    $50,000 to $59,999',
 '    $60,000 to $69,999',
 '    $70,000 to $79,999',
 '    $80,000 to $89,999',
 '    $90,000 to $99,999',
 '    $100,000 and over',
 '      $100,000 to $149,999',
 '      $150,000 and over',
 'Total - After-tax income groups in 2020 for the population aged 15 years and over in private households - 25% sample data',
 '  Without after-tax income',
 '  With after-tax income',
 '    Under $10,000 (including loss)',
 '    $10,000 to $19,999',
 '    $20,000 to $29,999',
 '    $30,000 to $39,999',
 '    $40,000 to $49,999',
 '    $50,000 to $59,999',
 '    $60,000 to $69,999',
 '    $70,000 to $79,999',
 '    $80,000 to $89,999',
 '    $90,000 to $99,999',
 '    $100,000 and over',
 '      $100,000 to $124,999',
 '      $125,000 and over',
 'Total - Employment income groups in 2020 for the population aged 15 years and over in private households - 25% sample data',
 '  Without employment income',
 '  With employment income',
 '    Under $5,000 (including loss)',
 '    $5,000 to $9,999',
 '    $10,000 to $19,999',
 '    $20,000 to $29,999',
 '    $30,000 to $39,999',
 '    $40,000 to $49,999',
 '    $50,000 to $59,999',
 '    $60,000 to $69,999',
 '    $70,000 to $79,999',
 '    $80,000 to $89,999',
 '    $90,000 to $99,999',
 '    $100,000 and over',
 '      $100,000 to $124,999',
 '      $125,000 and over',
 'Total - Income statistics in 2019 for the population aged 15 years and over in private households - 25% sample data',
 '  Number of total income recipients aged 15 years and over in private households in 2019 - 25% sample data',
 '    Median total income in 2019 among recipients ($)',
 '    Average total income in 2019 among recipients ($)',
 '  Number of after-tax income recipients aged 15 years and over in private households in 2019 - 25% sample data',
 '    Median after-tax income in 2019 among recipients ($)',
 '    Average after-tax income in 2019  among recipients ($)',
 '  Number of market income recipients aged 15 years and over in private households in 2019 - 25% sample data',
 '    Median market income in 2019 among recipients ($)',
 '    Average market income in 2019 among recipients ($)',
 '  Number of employment income recipients aged 15 years and over in private households in 2019 - 25% sample data',
 '    Median employment income in 2019 among recipients ($)',
 '    Average employment income in 2019 among recipients ($)',
 '  Number of government transfers recipients aged 15 years and over in private households in 2019 - 25% sample data',
 '    Median government transfers in 2019 among recipients ($)',
 '    Average government transfers in 2019 among recipients ($)',
 '  Number of employment insurance benefits recipients aged 15 years and over in private households in 2019 - 25% sample data',
 '    Median employment insurance benefits in 2019 among recipients ($)',
 '    Average employment insurance benefits in 2019 among recipients ($)',
 'Composition of total income in 2019 of the population aged 15 years and over in private households (%) - 25% sample data',
 '  Market income (%)',
 '    Employment income (%)',
 '  Government transfers (%)',
 '    Employment insurance benefits (%)',
 'Total - Income statistics for persons aged 15 years and over not in economic families in private households - 25% sample data',
 '  Median total income in 2020 ($)',
 '  Average total income in 2020 ($)',
 '  Median after-tax income in 2020 ($)',
 '  Average after-tax income in 2020 ($)',
 'Total - LIM low-income status in 2020 for the population in private households - 25% sample data',
 '  0 to 17 years',
 '    0 to 5 years',
 '  18 to 64 years',
 '  65 years and over',
 'In low income based on the Low-income measure, after tax (LIM-AT)',
 '  0 to 17 years',
 '    0 to 5 years',
 '  18 to 64 years',
 '  65 years and over',
 'Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)',
 '  0 to 17 years (%)',
 '    0 to 5 years (%)',
 '  18 to 64 years (%)',
 '  65 years and over (%)',
 'Total - LICO low-income status in 2020 for the population in private households to whom the low-income concept is applicable - 25% sample data',
 '  0 to 17 years',
 '    0 to 5 years',
 '  18 to 64 years',
 '  65 years and over',
 'In low income based on the Low-income cut-offs, after tax (LICO-AT)',
 '  0 to 17 years',
 '    0 to 5 years',
 '  18 to 64 years',
 '  65 years and over',
 'Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)',
 '  0 to 17 years (%)',
 '    0 to 5 years (%)',
 '  18 to 64 years (%)',
 '  65 years and over (%)',
 'Total - Adjusted after-tax family income decile group for the population in private households - 25% sample data',
 '  In bottom half of the distribution',
 '    In bottom decile',
 '    In second decile',
 '    In third decile',
 '    In fourth decile',
 '    In fifth decile',
 '  In top half of the distribution',
 '    In sixth decile',
 '    In seventh decile',
 '    In eighth decile',
 '    In ninth decile',
 '    In top decile',
 'Total - Inequality measures for the population in private households - 25% sample data',
 '  Gini index on adjusted household total income',
 '  Gini index on adjusted household market income',
 '  Gini index on adjusted household after-tax income',
 '  P90/P10 ratio on adjusted household after-tax income',
 'Total - Occupied private dwellings by structural type of dwelling - 25% sample data',
 '  Single-detached house',
 '  Semi-detached house',
 '  Row house',
 '  Apartment or flat in a duplex',
 '  Apartment in a building that has fewer than five storeys',
 '  Apartment in a building that has five or more storeys',
 '  Other single-attached house',
 '  Movable dwelling',
 'Total - Private households by household size - 25% sample data',
 '  1 person',
 '  2 persons',
 '  3 persons',
 '  4 persons',
 '  5 or more persons',
 'Average household size',
 'Total - Household type - 25% sample data',
 '  One-census-family households without additional persons',
 '    Couple-family households',
 '      With children',
 '      Without children',
 '    One-parent-family households',
 '  Multigenerational households',
 '  Multiple-census-family households',
 '  One-census-family households with additional persons',
 '  Two-or-more-person non-census-family households',
 '  One-person households',
 'Total - Income statistics for private households - 25% sample data',
 '  Median total income of household in 2020 ($)',
 '  Average total income of household in 2020 ($)',
 '  Median after-tax income of household in 2020 ($)',
 '  Average after-tax income of household in 2020 ($)',
 'Total - Income statistics for one-person private households - 25% sample data',
 '  Median total income of one-person households in 2020 ($)',
 '  Average total income of one-person households in 2020 ($)',
 '  Median after-tax income of one-person households in 2020 ($)',
 '  Average after-tax income of one-person households in 2020 ($)',
 'Total - Income statistics for two-or-more-persons private households - 25% sample data',
 '  Median total income of two-or-more-person households in 2020 ($)',
 '  Average total income of two-or-more-person households in 2020 ($)',
 '  Median after-tax income of two-or-more-person households in 2020 ($)',
 '  Average after-tax income of two-or-more-person households in 2020 ($)',
 'Total - Household total income groups in 2020 for private households - 25% sample data',
 '  Under $5,000',
 '  $5,000 to $9,999',
 '  $10,000 to $14,999',
 '  $15,000 to $19,999',
 '  $20,000 to $24,999',
 '  $25,000 to $29,999',
 '  $30,000 to $34,999',
 '  $35,000 to $39,999',
 '  $40,000 to $44,999',
 '  $45,000 to $49,999',
 '  $50,000 to $59,999',
 '  $60,000 to $69,999',
 '  $70,000 to $79,999',
 '  $80,000 to $89,999',
 '  $90,000 to $99,999',
 '  $100,000 and over',
 '    $100,000 to $124,999',
 '    $125,000 to $149,999',
 '    $150,000 to $199,999',
 '    $200,000 and over',
 'Total - Household after-tax income groups in 2020 for private households - 25% sample data',
 '  Under $5,000',
 '  $5,000 to $9,999',
 '  $10,000 to $14,999',
 '  $15,000 to $19,999',
 '  $20,000 to $24,999',
 '  $25,000 to $29,999',
 '  $30,000 to $34,999',
 '  $35,000 to $39,999',
 '  $40,000 to $44,999',
 '  $45,000 to $49,999',
 '  $50,000 to $59,999',
 '  $60,000 to $69,999',
 '  $70,000 to $79,999',
 '  $80,000 to $89,999',
 '  $90,000 to $99,999',
 '  $100,000 and over',
 '    $100,000 to $124,999',
 '    $125,000 to $149,999',
 '    $150,000 and over',
 'Total - Private households by tenure - 25% sample data',
 '  Owner',
 '  Renter',
 '  Dwelling provided by the local government, First Nation or Indian band',
 'Total - Occupied private dwellings by condominium status - 25% sample data',
 '  Condominium',
 '  Not condominium',
 'Total - Occupied private dwellings by number of bedrooms - 25% sample data',
 '  No bedrooms',
 '  1 bedroom',
 '  2 bedrooms',
 '  3 bedrooms',
 '  4 or more bedrooms',
 'Total - Occupied private dwellings by number of rooms - 25% sample data',
 '  1 to 4 rooms',
 '  5 rooms',
 '  6 rooms',
 '  7 rooms',
 '  8 or more rooms',
 'Average number of rooms per dwelling',
 'Total - Private households by number of persons per room - 25% sample data',
 '  One person or fewer per room',
 '  More than one person per room',
 'Total - Private households by housing suitability - 25% sample data',
 '  Suitable',
 '  Not suitable',
 'Total - Occupied private dwellings by period of construction - 25% sample data',
 '  1960 or before',
 '  1961 to 1980',
 '  1981 to 1990',
 '  1991 to 2000',
 '  2001 to 2005',
 '  2006 to 2010',
 '  2011 to 2015',
 '  2016 to 2021',
 'Total - Occupied private dwellings by dwelling condition - 25% sample data',
 '  Only regular maintenance and minor repairs needed',
 '  Major repairs needed',
 'Total - Private households by number of household maintainers - 25% sample data',
 '  One-maintainer household',
 '  Two-maintainer household',
 '  Three-or-more-maintainer household',
 'Total - Private households by age of primary household maintainers - 25% sample data',
 '  15 to 24 years',
 '  25 to 34 years',
 '  35 to 44 years',
 '  45 to 54 years',
 '  55 to 64 years',
 '  65 to 74 years',
 '  75 to 84 years',
 '  85 years and over',
 'Total - Occupied private dwellings by housing indicators - 25% sample data',
 "  Total - Households 'spending 30% or more of income on shelter costs' or 'not suitable' or 'major repairs needed'",
 '    Spending 30% or more of income on shelter costs only',
 '    Not suitable only',
 '    Major repairs needed only',
 "    'Spending 30% or more of income on shelter costs' and 'not suitable'",
 "    'Spending 30% or more of income on shelter costs' and 'major repairs needed'",
 "    'Not suitable' and 'major repairs needed'",
 "    'Spending 30% or more of income on shelter costs' and 'not suitable' and 'major repairs needed'",
 '  Acceptable housing',
 'Total - Owner and tenant households with household total income greater than zero, in non-farm, non-reserve private dwellings by shelter-cost-to-income ratio - 25% sample data',
 '  Spending less than 30% of income on shelter costs',
 '  Spending 30% or more of income on shelter costs',
 '    30% to less than 100%',
 'Total - Owner and tenant households with household total income greater than zero and shelter-cost-to-income ratio less than 100%, in non-farm, non-reserve private dwellings by core housing need - 25% sample data',
 '  In core need',
 '  Not in core need',
 'Total - Owner households in non-farm, non-reserve private dwellings - 25% sample data',
 '  % of owner households with a mortgage',
 '  % of owner households spending 30% or more of its income on shelter costs',
 '  % in core housing need',
 '  Median monthly shelter costs for owned dwellings ($)',
 '  Average monthly shelter costs for owned dwellings ($)',
 '  Median value of dwellings ($)',
 '  Average value of dwellings ($)',
 'Total - Tenant households in non-farm, non-reserve private dwellings - 25% sample data',
 '  % of tenant households in subsidized housing',
 '  % of tenant households spending 30% or more of its income on shelter costs',
 '  % in core housing need',
 '  Median monthly shelter costs for rented dwellings ($)',
 '  Average monthly shelter costs for rented dwellings ($)',
 'Total - Households living in a dwelling provided by the local government, First Nation or Indian band in non-farm private dwellings - 25% sample data',
 '  % of households living in a dwelling provided by the local government, First Nation or Indian band spending more than 30% on shelter costs',
 '  Median monthly shelter costs for dwellings provided by local government, First Nation or Indian band ($)',
 '  Average monthly shelter costs for dwellings provided by local government, First Nation or Indian band ($)',
 'Total - Census families in private households by family size - 25% sample data',
 '  2 persons',
 '  3 persons',
 '  4 persons',
 '  5 or more persons',
 'Average size of census families',
 'Total number of census families in private households - 25% sample data',
 '  Total couple families',
 '    Married couples',
 '      With children',
 '      Without children',
 '    Common-law couples',
 '      With children',
 '      Without children',
 '  Total one-parent families',
 '    in which the parent is a woman+',
 '    in which the parent is a man+',
 'Average number of children in census families with children',
 'Total - Income statistics for economic families in private households - 25% sample data',
 '  Median total income of economic family in 2020 ($)',
 '  Average total income of economic family in 2020 ($)',
 '  Median after-tax income of economic family in 2020 ($)',
 '  Average after-tax income of economic family in 2020 ($)',
 '  Average family size of economic families',
 'Total - Income statistics for economic families in private households - 25% sample data',
 '  Median total income of couple-only economic family in 2020 ($)',
 '  Average total income of couple-only economic family in 2020 ($)',
 '  Median after-tax income of couple-only economic family in 2020 ($)',
 '  Average after-tax income of economic family in 2020 ($)',
 '  Average family size of couple-only economic families',
 'Total - Income statistics for couple-with-children economic families in private households - 25% sample data',
 '  Median total income of couple-with-children economic family in 2020 ($)',
 '  Average total income of couple-with-children economic family in 2020 ($)',
 '  Median after-tax income of couple-with-children economic family in 2020 ($)',
 '  Average after-tax income of couple-with-children economic family in 2020 ($)',
 '  Average family size of couple-with-children economic families',
 'Total - Income statistics for one-parent economic families in private households - 25% sample data',
 '  Median total income of one-parent economic family in 2020 ($)',
 '  Average total income of one-parent economic family in 2020 ($)',
 '  Median after-tax income of one-parent economic family in 2020 ($)',
 '  Average after-tax income of one-parent economic family in 2020 ($)',
 '  Average family size of one-parent economic families',
 'Total - Knowledge of official languages for the population in private households - 25% sample data',
 '  English only',
 '  French only',

## **Child Care Centre Data**

In [6]:
child_centres["dropinHours"].unique()

array(['Wednesday: 9:00 a.m. - 11:30 a.m.  ', None,
       'Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.  ; 1:30 p.m. - 2:30 p.m.   | Tuesday: 9:00 a.m. - noon  ; 10:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:30 p.m.   | Wednesday: 9:00 a.m. - noon  ; 10:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:30 p.m.   | Thursday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.  ; 4:30 p.m. - 7:00 p.m.   | Friday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.   | Saturday: 9:30 a.m. - noon  ',
       'Monday: 10:00 a.m. - noon  ; 3:30 p.m. - 6:00 p.m.   | Tuesday: 2:00 p.m. - 4:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 2:00 p.m. - 4:00 p.m.   | Friday: 10:00 a.m. - noon   | Saturday: 10:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:30 p.m.   | Tuesday: 1:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - 11:30 a.m.   | Thursday: 1:00 p.m. - 3:30 p.m.   | Friday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:30 p.m.  ',
       'Wednesday: 1:00 p.m. - 3:30 p.m.  ',
       'Saturday: 9:00 a.m. - 11:00 a.m.  ',
       'Monday: 2:00 p.m. - 4:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.   | Friday: 10:00 a.m. - noon  ',
       'Monday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Tuesday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Wednesday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon   | Thursday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon   | Friday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Saturday: 9:00 a.m. - noon  ',
       'Monday: 1:00 p.m. - 4:00 p.m.   | Tuesday: 1:00 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - noon   | Friday: 10:00 a.m. - noon  ',
       'Monday: 5:00 p.m. - 7:00 p.m.   | Tuesday: 5:00 p.m. - 7:00 p.m.   | Saturday: 9:00 a.m. - 11:00 a.m.  ',
       'Monday: noon - 3:00 p.m.  ; 4:00 p.m. - 8:00 p.m.   | Tuesday: noon - 3:00 p.m.  ; 4:00 p.m. - 8:00 p.m.   | Wednesday: 9:30 a.m. - 3:00 p.m.  ; 4:00 p.m. - 8:00 p.m.  ; 9:30 a.m. - 3:00 p.m.  ; 4:00 p.m. - 8:00 p.m.   | Thursday: 9:30 a.m. - 12:30 p.m.  ; 1:30 p.m. - 5:30 p.m.  ; 9:30 a.m. - 12:30 p.m.  ; 1:30 p.m. - 5:30 p.m.   | Friday: 9:30 a.m. - 12:30 p.m.  ; 1:30 p.m. - 5:30 p.m.  ; 9:30 a.m. - 12:30 p.m.  ; 1:30 p.m. - 5:30 p.m.   | Saturday: 12:30 p.m. - 3:30 p.m.  ',
       'Tuesday: 3:30 p.m. - 5:00 p.m.   | Thursday: 9:30 a.m. - 11:00 a.m.  ',
       'Thursday: 4:00 p.m. - 5:15 p.m.  ',
       'Monday: 9:00 a.m. - 1:00 p.m.   | Tuesday: 9:00 a.m. - 1:00 p.m.   | Wednesday: 9:00 a.m. - 1:00 p.m.   | Thursday: 9:00 a.m. - 1:00 p.m.   | Friday: 9:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:30 a.m. - 2:30 p.m.  ; 9:30 a.m. - 6:00 p.m.   | Tuesday: 9:30 a.m. - 12:30 p.m.   | Wednesday: 9:30 a.m. - 2:30 p.m.   | Thursday: 9:30 a.m. - 12:30 p.m.   | Friday: 9:30 a.m. - 2:30 p.m.   | Saturday: 9:30 a.m. - 3:00 p.m.  ',
       'Monday: 10:00 a.m. - 1:00 p.m.   | Tuesday: 1:00 p.m. - 3:45 p.m.   | Thursday: 1:00 p.m. - 3:45 p.m.  ',
       'Wednesday: 9:30 a.m. - 1:00 p.m.   | Friday: 9:30 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - 2:00 p.m.   | Tuesday: 9:00 a.m. - 2:00 p.m.   | Wednesday: 9:00 a.m. - 2:00 p.m.   | Thursday: 9:00 a.m. - 2:00 p.m.  ',
       'Monday: 9:00 a.m. - 3:00 p.m.  ; 5:00 p.m. - 7:00 p.m.   | Tuesday: 1:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Thursday: 1:30 p.m. - 3:30 p.m.  ; 4:00 p.m. - 7:00 p.m.   | Friday: 9:00 a.m. - noon   | Saturday: 10:00 a.m. - 1:00 p.m.  ',
       'Monday: 12:30 p.m. - 4:15 p.m.   | Tuesday: 12:30 p.m. - 4:15 p.m.   | Wednesday: 12:30 p.m. - 4:15 p.m.   | Thursday: 12:30 p.m. - 4:15 p.m.   | Friday: 12:30 p.m. - 4:15 p.m.   | Saturday: 12:30 p.m. - 3:00 p.m.  ',
       'Monday: 8:45 a.m. - 12:30 p.m.   | Tuesday: 8:45 a.m. - 12:30 p.m.   | Wednesday: 8:45 a.m. - 12:30 p.m.   | Thursday: 8:45 a.m. - 12:30 p.m.   | Friday: 8:45 a.m. - 12:30 p.m.  ',
       'Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.   | Tuesday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.  ; 4:30 p.m. - 7:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.  ; 4:30 p.m. - 7:00 p.m.   | Thursday: 9:00 a.m. - noon  ; 4:30 p.m. - 7:00 p.m.   | Friday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.   | Saturday: 9:30 a.m. - 12:30 p.m.  ',
       'Tuesday: 1:30 p.m. - 3:00 p.m.  ',
       'Monday: 9:15 a.m. - 2:15 p.m.   | Tuesday: 9:15 a.m. - 2:15 p.m.   | Wednesday: 9:15 a.m. - 2:15 p.m.   | Thursday: 9:15 a.m. - 2:15 p.m.  ',
       'Monday: 9:00 a.m. - 11:30 a.m.   | Tuesday: 9:00 a.m. - 11:30 a.m.   | Wednesday: 1:30 p.m. - 6:00 p.m.   | Thursday: 9:00 a.m. - 11:30 a.m.  ; 1:30 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - 11:30 a.m.  ',
       'Tuesday: 10:00 a.m. - 1:00 p.m.   | Thursday: 10:00 a.m. - 1:00 p.m.   | Saturday: 10:00 a.m. - 1:00 p.m.  ',
       'Monday: 8:45 a.m. - 1:45 p.m.   | Tuesday: 8:45 a.m. - 1:45 p.m.   | Wednesday: 8:45 a.m. - 1:45 p.m.   | Thursday: 8:45 a.m. - 1:45 p.m.  ',
       'Monday: 9:00 a.m. - 1:00 p.m.   | Tuesday: 9:00 a.m. - 1:00 p.m.   | Wednesday: 9:00 a.m. - 1:00 p.m.  ; 4:00 p.m. - 6:00 p.m.   | Thursday: 9:00 a.m. - 1:00 p.m.   | Friday: 9:00 a.m. - 1:00 p.m.   | Saturday: 9:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.   | Tuesday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.  ',
       'Monday: 10:00 a.m. - 2:00 p.m.   | Tuesday: 10:00 a.m. - 2:00 p.m.   | Wednesday: 10:00 a.m. - 2:00 p.m.   | Thursday: 10:00 a.m. - 2:00 p.m.   | Friday: 10:00 a.m. - 2:00 p.m.  ',
       'Monday: 8:30 a.m. - 1:30 p.m.   | Tuesday: 8:30 a.m. - 1:30 p.m.   | Wednesday: 8:30 a.m. - 1:30 p.m.   | Thursday: 8:30 a.m. - 1:30 p.m.  ',
       'Monday: 8:45 a.m. - 12:45 p.m.   | Tuesday: 8:45 a.m. - 12:45 p.m.   | Wednesday: 8:45 a.m. - 12:45 p.m.   | Thursday: 8:45 a.m. - 12:45 p.m.   | Friday: 8:45 a.m. - 12:45 p.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Tuesday: 9:30 a.m. - noon   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 4:00 p.m.   | Thursday: 10:00 a.m. - noon   | Saturday: 9:30 a.m. - 11:00 a.m.  ; 11:00 a.m. - 12:30 p.m.  ',
       'Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.  ; noon - 6:00 p.m.   | Thursday: 9:00 a.m. - 3:00 p.m.   | Friday: 9:00 a.m. - 1:00 p.m.   | Saturday: 10:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 11:30 a.m.   | Thursday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Friday: 10:00 a.m. - 11:30 a.m.  ',
       'Monday: 9:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Tuesday: 2:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - noon   | Thursday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 2:30 p.m.   | Friday: 9:00 a.m. - 2:30 p.m.   | Saturday: 10:00 a.m. - 2:00 p.m.  ',
       'Monday: 8:00 a.m. - noon   | Tuesday: 8:00 a.m. - noon   | Wednesday: 8:00 a.m. - noon   | Thursday: 8:00 a.m. - noon   | Friday: 8:00 a.m. - noon  ',
       'Monday: 2:00 p.m. - 4:00 p.m.   | Tuesday: 9:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 3:00 p.m. - 4:00 p.m.   | Thursday: 2:00 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - noon   | Saturday: 10:00 a.m. - noon  ',
       'Tuesday: 9:30 a.m. - 3:00 p.m.   | Wednesday: 10:00 a.m. - 11:30 a.m.   | Thursday: 9:30 a.m. - 3:00 p.m.   | Friday: 9:30 a.m. - noon   | Saturday: 9:30 a.m. - noon  ',
       'Tuesday: 9:00 a.m. - noon   | Wednesday: 10:00 a.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 1:00 p.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 2:30 p.m.   | Wednesday: 9:00 a.m. - noon   | Saturday: 9:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 11:00 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.  ',
       'Tuesday: 9:30 a.m. - 11:00 a.m.  ',
       'Tuesday: 12:15 p.m. - 3:15 p.m.   | Wednesday: 8:30 a.m. - 11:30 a.m.  ; 12:15 p.m. - 3:15 p.m.  ; 9:00 a.m. - noon  ; 12:30 p.m. - 3:30 p.m.   | Thursday: 12:15 p.m. - 3:15 p.m.  ; 12:30 p.m. - 3:30 p.m.  ',
       'Monday: 10:30 a.m. - noon   | Wednesday: 10:30 a.m. - 12:30 p.m.  ',
       'Monday: 8:15 a.m. - 1:15 p.m.   | Tuesday: 8:15 a.m. - 1:15 p.m.   | Wednesday: 8:15 a.m. - 1:15 p.m.   | Thursday: 8:15 a.m. - 1:15 p.m.  ',
       'Monday: 8:30 a.m. - 12:30 p.m.   | Tuesday: 8:30 a.m. - 12:30 p.m.   | Wednesday: 8:30 a.m. - 12:30 p.m.   | Thursday: 8:30 a.m. - 12:30 p.m.   | Friday: 8:30 a.m. - 12:30 p.m.  ',
       'Sunday: 1:00 p.m. - 4:00 p.m.   | Monday: 9:30 a.m. - 1:00 p.m.   | Tuesday: 9:30 a.m. - 1:00 p.m.   | Wednesday: 9:30 a.m. - 3:00 p.m.   | Thursday: 9:30 a.m. - 1:00 p.m.   | Friday: 9:30 a.m. - 1:00 p.m.  ',
       'Monday: 10:30 a.m. - 4:00 p.m.   | Tuesday: 9:00 a.m. - 10:15 a.m.  ; 11:15 a.m. - 1:00 p.m.  ; 3:00 p.m. - 3:30 p.m.   | Wednesday: 10:00 a.m. - 10:30 a.m.  ; 11:00 a.m. - 11:30 a.m.  ; 12:30 p.m. - 2:00 p.m.  ; 3:00 p.m. - 5:00 p.m.   | Thursday: 10:00 a.m. - 1:00 p.m.  ; 3:00 p.m. - 5:00 p.m.   | Friday: 10:00 a.m. - 11:00 a.m.  ; noon - 3:00 p.m.  ; 4:00 p.m. - 5:00 p.m.   | Saturday: 3:00 p.m. - 3:30 p.m.  ; 4:00 p.m. - 5:00 p.m.  ',
       'Wednesday: 10:00 a.m. - 11:30 a.m.   | Friday: 10:00 a.m. - 11:30 a.m.  ',
       'Monday: 9:00 a.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 3:00 p.m.   | Friday: 9:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Friday: 9:00 a.m. - 11:30 a.m.   | Saturday: 10:00 a.m. - noon  ; 12:30 p.m. - 2:00 p.m.  ',
       'Monday: 9:00 a.m. - noon   | Tuesday: 1:00 p.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 11:00 a.m.   | Tuesday: 10:30 a.m. - 11:30 a.m.   | Wednesday: 9:00 a.m. - 10:00 a.m.  ; 9:00 a.m. - 11:00 a.m.   | Thursday: 10:00 a.m. - 11:00 a.m.  ; 10:30 a.m. - 11:30 a.m.  ; 10:00 a.m. - 11:00 a.m.   | Friday: 9:00 a.m. - 11:00 a.m.  ',
       'Monday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.  ; 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Tuesday: 1:00 p.m. - 3:00 p.m.  ; 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Wednesday: 1:00 p.m. - 3:00 p.m.  ; 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 11:30 a.m.   | Friday: 1:00 p.m. - 3:00 p.m.  ; 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Saturday: 9:00 a.m. - 2:00 p.m.  ',
       'Tuesday: 9:30 a.m. - 11:30 a.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ',
       'Wednesday: 10:30 a.m. - 11:30 a.m.  ',
       'Wednesday: 10:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 3:00 p.m.   | Friday: 9:00 a.m. - 3:00 p.m.  ',
       'Tuesday: 10:30 a.m. - 11:30 a.m.  ; 1:00 p.m. - 2:00 p.m.  ',
       'Monday: 9:15 a.m. - 1:15 p.m.   | Tuesday: 9:15 a.m. - 1:15 p.m.   | Wednesday: 9:15 a.m. - 1:15 p.m.   | Thursday: 9:15 a.m. - 1:15 p.m.   | Friday: 9:15 a.m. - 1:15 p.m.  ',
       'Monday: 9:00 a.m. - 1:30 p.m.   | Tuesday: 9:00 a.m. - 1:30 p.m.   | Wednesday: 9:00 a.m. - noon  ; 12:30 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - 1:30 p.m.  ',
       'Monday: 9:00 a.m. - 7:00 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Friday: 9:00 a.m. - 3:00 p.m.   | Saturday: 9:00 a.m. - noon  ',
       'Monday: 9:15 a.m. - noon  ; noon - 3:00 p.m.   | Tuesday: 9:15 a.m. - noon  ; noon - 3:00 p.m.  ; 1:00 p.m. - 3:00 p.m.  ; 3:00 p.m. - 7:00 p.m.   | Wednesday: 9:15 a.m. - noon  ; noon - 4:30 p.m.   | Thursday: 9:15 a.m. - noon  ; noon - 3:00 p.m.   | Friday: 9:30 a.m. - 3:30 p.m.  ',
       'Monday: 10:00 a.m. - 11:30 a.m.   | Tuesday: 10:00 a.m. - noon  ; 3:30 p.m. - 6:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 2:00 p.m. - 3:30 p.m.  ; 4:30 p.m. - 6:30 p.m.   | Saturday: 9:00 a.m. - noon  ',
       'Friday: 9:30 a.m. - 11:30 a.m.  ',
       'Monday: 9:00 a.m. - noon   | Tuesday: 9:00 a.m. - noon   | Wednesday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 1:00 p.m. - 2:45 p.m.   | Thursday: 1:00 p.m. - 2:45 p.m.  ',
       'Tuesday: 9:00 a.m. - noon  ; 4:00 p.m. - 6:00 p.m.   | Wednesday: 9:00 a.m. - noon   | Thursday: 9:00 a.m. - noon  ; 1:30 p.m. - 3:30 p.m.   | Saturday: 9:30 a.m. - noon  ',
       'Monday: 9:00 a.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - noon   | Wednesday: 9:00 a.m. - noon  ; 5:00 p.m. - 7:00 p.m.   | Saturday: 9:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - 2:30 p.m.  ',
       'Tuesday: 9:00 a.m. - noon   | Wednesday: 9:00 a.m. - noon   | Thursday: 9:00 a.m. - noon  ',
       'Monday: 3:30 p.m. - 5:00 p.m.  ',
       'Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.  ; 5:00 p.m. - 7:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 2:00 p.m.  ; 2:30 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - noon   | Saturday: 9:30 a.m. - 11:30 a.m.  ',
       'Sunday: 9:30 a.m. - 11:30 a.m.   | Monday: 9:30 a.m. - 11:30 a.m.   | Tuesday: 9:30 a.m. - 11:00 a.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 6:00 p.m. - 7:30 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ',
       'Friday: 9:30 a.m. - 11:00 a.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 6:00 p.m. - 7:30 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 3:30 p.m. - 5:00 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 6:00 p.m. - 7:30 p.m.   | Saturday: 9:30 a.m. - 11:30 a.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.   | Tuesday: 1:30 p.m. - 3:30 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 4:30 p.m. - 6:30 p.m.  ; 9:30 a.m. - 11:30 a.m.   | Thursday: 9:30 a.m. - 11:30 a.m.   | Friday: 1:30 p.m. - 3:30 p.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.   | Thursday: 1:30 p.m. - 3:00 p.m.  ',
       'Thursday: 10:30 a.m. - 12:30 p.m.  ',
       'Monday: 2:00 p.m. - 6:00 p.m.   | Tuesday: noon - 4:00 p.m.   | Wednesday: noon - 4:00 p.m.   | Thursday: noon - 4:00 p.m.   | Friday: noon - 3:00 p.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 4:00 p.m. - 5:00 p.m.   | Tuesday: 9:30 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Thursday: 9:30 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Friday: 9:30 a.m. - 11:30 a.m.  ',
       'Sunday: 1:30 p.m. - 6:30 p.m.   | Monday: 9:00 a.m. - 12:30 p.m.   | Tuesday: 9:00 a.m. - 12:30 p.m.   | Wednesday: 9:00 a.m. - 12:30 p.m.   | Thursday: 1:30 p.m. - 4:30 p.m.   | Friday: 9:00 a.m. - 12:30 p.m.   | Saturday: 9:30 a.m. - noon  ',
       'Thursday: 9:30 a.m. - 11:30 a.m.   | Friday: 9:00 a.m. - 11:30 a.m.  ',
       'Monday: 9:00 a.m. - noon  ; 2:30 p.m. - 4:00 p.m.   | Tuesday: 9:00 a.m. - noon  ; 1:30 p.m. - 3:00 p.m.  ; 3:30 p.m. - 5:30 p.m.   | Wednesday: 9:00 a.m. - noon  ; 1:30 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - noon  ; 1:30 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - noon  ; 2:30 p.m. - 4:00 p.m.   | Saturday: 9:00 a.m. - 11:30 a.m.  ',
       'Saturday: 9:45 a.m. - 12:30 p.m.  ',
       'Monday: 10:30 a.m. - 1:00 p.m.   | Thursday: 2:00 p.m. - 4:30 p.m.  ',
       'Monday: 4:30 p.m. - 7:30 p.m.   | Tuesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Friday: 10:00 a.m. - noon  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 10:30 a.m. - 11:30 a.m.   | Tuesday: 9:30 a.m. - 10:30 a.m.  ; 10:30 a.m. - 11:30 a.m.  ; 2:00 p.m. - 4:00 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ; 4:30 p.m. - 5:30 p.m.   | Friday: 9:30 a.m. - 11:30 a.m.  ; 10:30 a.m. - 11:30 a.m.   | Saturday: 10:00 a.m. - noon  ',
       'Monday: 7:45 a.m. - 11:45 a.m.   | Tuesday: 7:45 a.m. - 11:45 a.m.   | Wednesday: 7:45 a.m. - 11:45 a.m.   | Thursday: 7:45 a.m. - 11:45 a.m.   | Friday: 7:45 a.m. - 11:45 a.m.  ',
       'Monday: 9:00 a.m. - 12:30 p.m.   | Tuesday: 9:00 a.m. - 12:30 p.m.   | Wednesday: 9:00 a.m. - 12:30 p.m.  ; 3:30 p.m. - 4:30 p.m.   | Thursday: 9:00 a.m. - 12:30 p.m.   | Friday: 9:00 a.m. - 12:30 p.m.  ',
       'Monday: 9:00 a.m. - 11:30 a.m.   | Tuesday: 9:00 a.m. - 11:30 a.m.   | Thursday: 9:00 a.m. - 11:30 a.m.   | Friday: 9:30 a.m. - 11:30 a.m.  ',
       'Thursday: 9:30 a.m. - 11:30 a.m.  ',
       'Monday: 10:30 a.m. - 11:30 a.m.  ',
       'Tuesday: 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 5:00 p.m. - 6:30 p.m.   | Wednesday: 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.   | Thursday: 8:30 a.m. - 11:30 a.m.   | Friday: 1:30 p.m. - 3:30 p.m.  ; 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Saturday: 1:30 p.m. - 3:30 p.m.  ',
       'Monday: 8:15 a.m. - 12:15 p.m.   | Tuesday: 8:15 a.m. - 12:15 p.m.   | Wednesday: 8:15 a.m. - 12:15 p.m.   | Thursday: 8:15 a.m. - 12:15 p.m.   | Friday: 8:15 a.m. - 12:15 p.m.  ',
       'Monday: 9:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Tuesday: 2:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 8:30 a.m. - 4:15 p.m.   | Tuesday: 8:45 a.m. - 6:00 p.m.   | Wednesday: 8:45 a.m. - 6:00 p.m.   | Thursday: 8:45 a.m. - 4:15 p.m.   | Friday: 8:45 a.m. - 4:15 p.m.  ',
       'Monday: 9:00 a.m. - 1:00 p.m.  ; 2:30 p.m. - 6:00 p.m.   | Tuesday: 9:00 a.m. - 1:00 p.m.  ; 2:30 p.m. - 6:00 p.m.   | Wednesday: 9:00 a.m. - 1:00 p.m.  ; 2:30 p.m. - 6:00 p.m.   | Thursday: 9:00 a.m. - 1:00 p.m.  ; 2:30 p.m. - 6:00 p.m.   | Friday: 9:00 a.m. - 1:00 p.m.   | Saturday: 9:00 a.m. - 11:00 a.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Friday: 9:30 a.m. - 11:30 a.m.   | Saturday: 9:30 a.m. - noon  ; 12:30 p.m. - 2:00 p.m.  ',
       'Tuesday: 9:30 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Wednesday: 11:30 a.m. - 3:00 p.m.   | Thursday: 9:30 a.m. - 10:30 a.m.  ; 11:30 a.m. - 1:00 p.m.   | Friday: 4:00 p.m. - 6:00 p.m.  ',
       'Monday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Tuesday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Thursday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Friday: 10:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - noon   | Wednesday: 1:30 p.m. - 3:30 p.m.   | Thursday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 9:30 a.m. - noon  ; 1:00 p.m. - 3:00 p.m.   | Tuesday: 1:00 p.m. - 3:00 p.m.   | Wednesday: 9:30 a.m. - noon   | Thursday: 9:30 a.m. - noon  ; 1:00 p.m. - 2:30 p.m.  ; 4:00 p.m. - 6:30 p.m.   | Friday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.  ',
       'Monday: 9:00 a.m. - 1:30 p.m.   | Tuesday: 1:00 p.m. - 5:30 p.m.   | Thursday: 9:00 a.m. - 1:30 p.m.   | Friday: 9:00 a.m. - 1:30 p.m.   | Saturday: 9:30 a.m. - 12:30 p.m.  ',

In [7]:
def categorize_hours(text):
    if pd.isna(text) or not isinstance(text, str) or text.strip() == "":
        return "Other"
    
    t = text.lower()
    
    # Detect days
    days = re.findall(r"(monday|tuesday|wednesday|thursday|friday|saturday|sunday)", t)
    unique_days = set(days)
    
    # Detect if weekend present
    weekend = bool({"saturday", "sunday"} & unique_days)
    
    # Detect time ranges
    evening = bool(re.search(r"(5|6|7|8|9):\d{0,2}\s*p\.?m\.?", t))
    morning = bool(re.search(r"(7|8|9|10|11):\d{0,2}\s*a\.?m\.?", t))
    afternoon = bool(re.search(r"(12|1|2|3|4):\d{0,2}\s*p\.?m\.?", t))
    
    # Apply logic
    if weekend:
        return "Weekend available"
    elif evening:
        return "Evening available"
    elif morning and afternoon:
        return "Full day"
    elif morning:
        return "Morning only"
    elif afternoon:
        return "Afternoon only"
    else:
        return "Other"

child_centres["hourCategory"] = child_centres["dropinHours"].apply(categorize_hours)

child_centres["hourCategory"]

0           Morning only
1                  Other
2      Weekend available
3      Weekend available
4               Full day
             ...
225    Weekend available
226    Weekend available
227                Other
228             Full day
229    Evening available
Name: hourCategory, Length: 230, dtype: object

In [8]:
child_centres["hourCategory"].unique()

array(['Morning only', 'Other', 'Weekend available', 'Full day',
       'Afternoon only', 'Evening available'], dtype=object)

In [9]:
child_centres.isna().sum()

_id                          0
service_system_manager       0
agency                       0
loc_id                       0
program_name                 0
languages                    0
french_language_program    228
indigenous_program         223
programTypes                 0
serviceName                 19
buildingName                57
address                      0
full_address                 0
major_intersection         188
ward                         0
ward_name                    0
located_in_school            0
school_name                118
lat                          0
lng                          0
website                     23
website_name                 0
website_description          0
consultant_fullname          0
consultant_phone             0
email                        0
contact_fullname             0
contact_title              103
phone                        0
contact_email                0
dropinHours                 19
registeredHours            168
virtualHours               230
centre_type                  0
geometry                     0
hourCategory                 0
dtype: int64

In [10]:
child_centres['address']

0            101 Spruce St
1           1033 King St W
2      2555 Eglinton Ave E
3         2700 Dufferin St
4             38 Regent St
              ...
225     160 Eglinton Ave E
226      30 Sheppard Ave E
227       1785 Finch Ave W
228      25 Yorkwoods Gate
229       3090 Kingston Rd
Name: address, Length: 230, dtype: object

In [11]:
child_centres.to_file('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/child_centres_clean.geojson', driver="GeoJSON")

In [12]:
cols1 = set(transpose.columns)
cols2 = set(child_centres.columns)
cols3 = set(improvement_areas.columns)

matching_columns = cols1.intersection(cols2)
matching_columns2 = cols1.intersection(cols3)
matching_columns3 = cols2.intersection(cols3)
# joining isn't possible

In [13]:
child_centres["ward"].nunique()

25

## **Neighbourhood Improvement Areas Data**

In [14]:
improvement_areas

,_id,AREA_ID,DATE_EFFECTIVE,DATE_EXPIRY,AREA_ATTR_ID,AREA_TYPE_ID,PARENT_AREA_ID,AREA_TYPE,AREA_CLASS_ID,AREA_CLASS,AREA_SHORT_CODE,AREA_LONG_CODE,AREA_NAME,AREA_DESC,FEATURE_CODE,FEATURE_CODE_DESC,TRANS_ID_CREATE,TRANS_ID_EXPIRE,OBJECTID,geometry
0,1,2502359.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022874.0,602.0,None,CNBH,None,None,155,155,Downsview,Downsview (155),None,None,344709.0,-1.0,17824849,"MULTIPOLYGON (((-79.46453 43.75014, -79.4643 4..."
1,2,2502358.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022873.0,602.0,None,CNBH,None,None,154,154,Oakdale-Beverley Heights,Oakdale-Beverley Heights (154),None,None,344709.0,-1.0,17824865,"MULTIPOLYGON (((-79.51192 43.73457, -79.51154 ..."
2,3,2502346.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022861.0,602.0,None,CNBH,None,None,142,142,Woburn North,Woburn North (142),None,None,344709.0,-1.0,17825057,"MULTIPOLYGON (((-79.22448 43.78841, -79.2243 4..."
3,4,2502345.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022860.0,602.0,None,CNBH,None,None,141,141,Golfdale-Cedarbrae-Woburn,Golfdale-Cedarbrae-Woburn (141),None,None,344709.0,-1.0,17825073,"MULTIPOLYGON (((-79.21948 43.77179, -79.21868 ..."
4,5,2502343.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022858.0,602.0,None,CNBH,None,None,139,139,Scarborough Village,Scarborough Village (139),None,None,344709.0,-1.0,17825105,"MULTIPOLYGON (((-79.20827 43.73757, -79.20761 ..."
5,6,2502342.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022857.0,602.0,None,CNBH,None,None,138,138,Eglinton East,Eglinton East (138),None,None,344709.0,-1.0,17825121,"MULTIPOLYGON (((-79.23641 43.75328, -79.23641 ..."
6,7,2502341.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022856.0,602.0,None,CNBH,None,None,136,136,West Hill,West Hill (136),None,None,344709.0,-1.0,17825137,"MULTIPOLYGON (((-79.18037 43.78098, -79.17996 ..."
7,8,2502340.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022855.0,602.0,None,CNBH,None,None,135,135,Morningside,Morningside (135),None,None,344709.0,-1.0,17825153,"MULTIPOLYGON (((-79.19436 43.78928, -79.19382 ..."
8,9,2502333.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022848.0,602.0,None,CNBH,None,None,125,125,Ionview,Ionview (125),None,None,344709.0,-1.0,17825265,"MULTIPOLYGON (((-79.27456 43.72322, -79.27485 ..."
9,10,2502332.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022847.0,602.0,None,CNBH,None,None,124,124,Kennedy Park,Kennedy Park (124),None,None,344709.0,-1.0,17825281,"MULTIPOLYGON (((-79.26894 43.71471, -79.27112 ..."
10,11,2502301.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022816.0,602.0,None,CNBH,None,None,091,091,Weston-Pelham Park,Weston-Pelham Park (91),None,None,344709.0,-1.0,17825777,"MULTIPOLYGON (((-79.45879 43.67927, -79.45796 ..."
11,12,2502299.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022814.0,602.0,None,CNBH,None,None,121,121,Oakridge,Oakridge (121),None,None,344709.0,-1.0,17825809,"MULTIPOLYGON (((-79.27892 43.70702, -79.27839 ..."
12,13,2502294.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022809.0,602.0,None,CNBH,None,None,115,115,Mount Dennis,Mount Dennis (115),None,None,344709.0,-1.0,17825889,"MULTIPOLYGON (((-79.50007 43.69424, -79.49764 ..."
13,14,2502292.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022807.0,602.0,None,CNBH,None,None,113,113,Weston,Weston (113),None,None,344709.0,-1.0,17825921,"MULTIPOLYGON (((-79.53086 43.71068, -79.53154 ..."
14,15,2502291.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022806.0,602.0,None,CNBH,None,None,112,112,Beechborough-Greenbrook,Beechborough-Greenbrook (112),None,None,344709.0,-1.0,17825937,"MULTIPOLYGON (((-79.48677 43.68752, -79.48708 ..."
15,16,2502290.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022805.0,602.0,None,CNBH,None,None,111,111,Rockcliffe-Smythe,Rockcliffe-Smythe (111),None,None,344709.0,-1.0,17825953,"MULTIPOLYGON (((-79.47515 43.68115, -79.47468 ..."
16,17,2502289.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022804.0,602.0,None,CNBH,None,None,110,110,Keelesdale-Eglinton West,Keelesdale-Eglinton West (110),None,None,344709.0,-1.0,17825969,"MULTIPOLYGON (((-79.4621 43.68572, -79.46202 4..."
17,18,2502283.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022798.0,602.0,None,CNBH,None,None,072,072,Regent Park,Regent Park (72),None,None,344709.0,-1.0,17826065,"MULTIPOLYGON (((-79.36344 43.65583, -79.36446 ..."
18,19,2502272.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022787.0,602.0,None,CNBH,None,None,061,061,Taylor-Massey,Taylor-Massey (61),None,None,344709.0,-1.0,17826241,"MULTIPOLYGON (((-79.29348 43.70302, -79.29314 ..."
19,20,2502264.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022779.0,602.0,None,CNBH,None,None,085,085,South Parkdale,South Parkdale (85),None,None,344709.0,-1.0,17826369,"MULTIPOLYGON (((-79.42146 43.64061, -79.42144 ..."
20,21,2502258.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022773.0,602.0,None,CNBH,None,None,044,044,Flemingdon Park,Flemingdon Park (44),None,None,344709.0,-1.0,17826465,"MULTIPOLYGON (((-79.32608 43.7204, -79.32564 4..."
21,22,2502257.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022772.0,602.0,None,CNBH,None,None,043,043,Victoria Village,Victoria Village (43),None,None,344709.0,-1.0,17826481,"MULTIPOLYGON (((-79.30676 43.73466, -79.30623 ..."
22,23,2502242.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022757.0,602.0,None,CNBH,None,None,028,028,Rustic,Rustic (28),None,None,344709.0,-1.0,17826721,"MULTIPOLYGON (((-79.50369 43.70292, -79.50384 ..."
23,24,2502241.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022756.0,602.0,None,CNBH,None,None,027,027,York University Heights,York University Heights (27),None,None,344709.0,-1.0,17826737,"MULTIPOLYGON (((-79.46847 43.77519, -79.46779 ..."
24,25,2502240.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022755.0,602.0,None,CNBH,None,None,025,025,Glenfield-Jane Heights,Glenfield-Jane Heights (25),None,None,344709.0,-1.0,17826753,"MULTIPOLYGON (((-79.50607 43.75643, -79.50626 ..."
25,26,2502237.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022752.0,602.0,None,CNBH,None,None,055,055,Thorncliffe Park,Thorncliffe Park (55),None,None,344709.0,-1.0,17826801,"MULTIPOLYGON (((-79.34777 43.71614, -79.34761 ..."
26,27,2502218.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022733.0,602.0,None,CNBH,None,None,006,006,Kingsview Village-The Westway,Kingsview Village-The Westway (6),None,None,344709.0,-1.0,17827105,"MULTIPOLYGON (((-79.53765 43.70832, -79.53741 ..."
27,28,2502217.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022732.0,602.0,None,CNBH,None,None,005,005,Elms-Old Rexdale,Elms-Old Rexdale (5),None,None,344709.0,-1.0,17827121,"MULTIPOLYGON (((-79.54677 43.73156, -79.54632 ..."
28,29,2502215.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022730.0,602.0,None,CNBH,None,None,003,003,Thistletown-Beaumond Heights,Thistletown-Beaumond Heights (3),None,None,344709.0,-1.0,17827153,"MULTIPOLYGON (((-79.56226 43.74373, -79.56234 ..."
29,30,2502214.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022729.0,602.0,None,CNBH,None,None,002,002,Mount Olive-Silverstone-Jamestown,Mount Olive-Silverstone-Jamestown (2),None,None,344709.0,-1.0,17827169,"MULTIPOLYGON (((-79.57938 43.76222, -79.57925 ..."
30,31,2502212.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022727.0,602.0,None,CNBH,None,None,024,024,Black Creek,Black Creek (24),None,None,344709.0,-1.0,17827201,"MULTIPOLYGON (((-79.51915 43.77399, -79.51901 ..."
31,32,2502210.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022725.0,602.0,None,CNBH,None,None,022,022,Humbermede,Humbermede (22),None,None,344709.0,-1.0,17827233,"MULTIPOLYGON (((-79.52813 43.74425, -79.52721 ..."
32,33,2502209.0,2022-04-11 21:27:23,3000/01/01 05:00:00,26022724.0,602.0,None,CNBH,None,None,021,021,Humber Summit,Humber Summit (21),None,None,344709.0,-1.0,17827249,"MULTIPOLYGON (((-79.53396 43.76886, -79.53227 ..."

In [15]:
len(improvement_areas)

33

In [16]:
# In 2022, Toronto designated 33 neighbourhoods as vulnerable areas compared to 14 in 2014.

(33 - 14) / 14 * 100

135.71428571428572

In [17]:
list(improvement_areas.columns)

['_id',
 'AREA_ID',
 'DATE_EFFECTIVE',
 'DATE_EXPIRY',
 'AREA_ATTR_ID',
 'AREA_TYPE_ID',
 'PARENT_AREA_ID',
 'AREA_TYPE',
 'AREA_CLASS_ID',
 'AREA_CLASS',
 'AREA_SHORT_CODE',
 'AREA_LONG_CODE',
 'AREA_NAME',
 'AREA_DESC',
 'FEATURE_CODE',
 'FEATURE_CODE_DESC',
 'TRANS_ID_CREATE',
 'TRANS_ID_EXPIRE',
 'OBJECTID',
 'geometry']

## **2021 Income Data**

In [26]:
df = pd.read_csv('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/2021-toronto-average-median-household-incomes.csv')
df
df.columns

Index(['Neighbourhood', 'Average Household Income Before Taxes',
       'Median Household Income Before Taxes',
       'Average Household Income After Taxes',
       'Median Household Income After Taxes'],
      dtype='object')

In [27]:
df2 = pd.read_csv('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/2021-household-income-ranges.csv')
df2
df2.rename(columns={'Unnamed: 0': 'Neighbourhood'}, inplace=True)
df2.columns

Index(['Neighbourhood', 'Less Than $20,000', '$20,000 to $39,999',
       '$40,000 to $59,999', '$60,000 to $79,999', '$80,000 to $99,999',
       '$100,000 And Over', 'Total'],
      dtype='object')

In [20]:
df.to_csv('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/2021-toronto-average-median-household-incomes.csv', index=False)
df2.to_csv('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/2021-household-income-ranges.csv', index=False)

## **Neighbourhood Data**

In [28]:
neighbourhoods = gpd.read_file('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/Neighbourhoods - 4326.geojson')
neighbourhoods.columns

Index(['_id', 'AREA_ID', 'AREA_ATTR_ID', 'PARENT_AREA_ID', 'AREA_SHORT_CODE',
       'AREA_LONG_CODE', 'AREA_NAME', 'AREA_DESC', 'CLASSIFICATION',
       'CLASSIFICATION_CODE', 'OBJECTID', 'geometry'],
      dtype='object')

In [29]:
improvement_areas.columns

Index(['_id', 'AREA_ID', 'DATE_EFFECTIVE', 'DATE_EXPIRY', 'AREA_ATTR_ID',
       'AREA_TYPE_ID', 'PARENT_AREA_ID', 'AREA_TYPE', 'AREA_CLASS_ID',
       'AREA_CLASS', 'AREA_SHORT_CODE', 'AREA_LONG_CODE', 'AREA_NAME',
       'AREA_DESC', 'FEATURE_CODE', 'FEATURE_CODE_DESC', 'TRANS_ID_CREATE',
       'TRANS_ID_EXPIRE', 'OBJECTID', 'geometry'],
      dtype='object')