In [1]:
import pandas as pd
import geopandas as gpd
import re
import numpy as np

In [ ]:
neighbour_profiles = pd.read_excel('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/neighbourhood-profiles-2021-158-model.xlsx') # demographic data 
child_centres = gpd.read_file('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/EarlyON Child and Family Centres Locations - geometry - 4326.geojson') # childcare centre location data
improvement_areas = gpd.read_file('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/Neighbourhood Improvement Areas - 4326.geojson') # neighbourhood improvement area location data
neighbourhoods = gpd.read_file('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/Neighbourhoods - 4326.geojson') # neighbourhood location data

In [3]:
neighbour_profiles
transpose = neighbour_profiles.set_index(neighbour_profiles.columns[0]).T # transpose data
transpose = transpose.reset_index().rename(columns={'index': 'Neighbourhood'}) # reset the index to make neighbourhood index
transpose

Neighbourhood Name,Neighbourhood,Neighbourhood Number,TSNS 2020 Designation,Total - Age groups of the population - 25% sample data,0 to 14 years,0 to 4 years,5 to 9 years,10 to 14 years,15 to 64 years,15 to 19 years,...,Between 9 a.m. and 11:59 a.m.,Between 12 p.m. and 4:59 a.m.,Total - Eligibility for instruction in the minority official language for the population in private households born in 2003 or later - 25% sample data,Children eligible for instruction in the minority official language,Children not eligible for instruction in the minority official language,"Total - Eligibility and instruction in the minority official language, for the population in private households born between 2003 and 2015 (inclusive) - 25% sample data",Children eligible for instruction in the minority official language,Eligible children who have been instructed in the minority official language at the primary or secondary level in Canada,Eligible children who have not been instructed in the minority official language at the primary or secondary level in Canada,Children not eligible for instruction in the minority official language
0,West Humber-Clairville,1,Not an NIA or Emerging Neighbourhood,33300,4295,1460,1345,1485,23640,1860,...,1665,2935,5430,410,5020,3875,335,255,75,3540
1,Mount Olive-Silverstone-Jamestown,2,Neighbourhood Improvement Area,31345,5690,1650,1860,2175,21490,2280,...,1145,2965,7285,510,6780,5540,395,245,145,5145
2,Thistletown-Beaumond Heights,3,Neighbourhood Improvement Area,9850,1495,505,540,455,6615,570,...,395,635,1860,180,1685,1325,120,75,45,1205
3,Rexdale-Kipling,4,Not an NIA or Emerging Neighbourhood,10375,1575,505,615,455,6950,515,...,425,775,1910,135,1770,1370,90,75,25,1275
4,Elms-Old Rexdale,5,Neighbourhood Improvement Area,9355,1610,440,480,685,6355,635,...,355,675,2015,95,1920,1520,70,60,10,1445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Yonge-Bay Corridor,170,Not an NIA or Emerging Neighbourhood,12645,970,500,270,200,10820,340,...,695,330,1075,50,1020,555,30,10,20,520
154,Junction-Wallace Emerson,171,Not an NIA or Emerging Neighbourhood,23180,3075,1135,1020,925,17200,750,...,1185,1105,3580,410,3170,2375,305,190,115,2075
155,Dovercourt Village,172,Not an NIA or Emerging Neighbourhood,12380,1365,445,430,490,9040,460,...,775,570,1665,175,1490,1190,130,95,35,1060
156,North Toronto,173,Not an NIA or Emerging Neighbourhood,15885,1315,535,390,390,12780,465,...,970,550,1620,145,1470,1050,95,65,30,955
157,South Eglinton-Davisville,174,Not an NIA or Emerging Neighbourhood,22735,2190,910,670,610,17495,575,...,1390,730,2570,265,2300,1580,155,105,45,1420

In [4]:
transpose.to_csv('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/neighbourhood_profiles_clean.csv', index=False)

In [ ]:
transpose[['Neighbourhood', '    Couple-family households', '      With children']]

Neighbourhood Name,Neighbourhood,With children,With children,With children
0,West Humber-Clairville,2945,3930,215
1,Mount Olive-Silverstone-Jamestown,2950,3605,275
2,Thistletown-Beaumond Heights,905,1105,100
3,Rexdale-Kipling,995,1115,110
4,Elms-Old Rexdale,740,895,100
...,...,...,...,...
153,Yonge-Bay Corridor,660,660,50
154,Junction-Wallace Emerson,2200,2185,340
155,Dovercourt Village,1070,1120,145
156,North Toronto,990,880,135
157,South Eglinton-Davisville,1585,1510,125

In [59]:
list(transpose['Neighbourhood'])

['West Humber-Clairville',
 'Mount Olive-Silverstone-Jamestown',
 'Thistletown-Beaumond Heights',
 'Rexdale-Kipling',
 'Elms-Old Rexdale',
 'Kingsview Village-The Westway',
 'Willowridge-Martingrove-Richview',
 'Humber Heights-Westmount',
 'Edenbridge-Humber Valley',
 'Princess-Rosethorn',
 'Eringate-Centennial-West Deane',
 'Markland Wood',
 'Etobicoke West Mall',
 'Kingsway South',
 'Stonegate-Queensway',
 'New Toronto',
 'Long Branch',
 'Alderwood',
 'Humber Summit',
 'Humbermede',
 'Pelmo Park-Humberlea',
 'Black Creek',
 'Glenfield-Jane Heights',
 'York University Heights',
 'Rustic',
 'Maple Leaf',
 'Brookhaven-Amesbury',
 'Yorkdale-Glen Park',
 'Englemount-Lawrence',
 'Clanton Park',
 'Bathurst Manor',
 'Westminster-Branson',
 'Newtonbrook West',
 'Willowdale West',
 'Lansing-Westgate',
 'Bedford Park-Nortown',
 'St.Andrew-Windfields',
 'Bridle Path-Sunnybrook-York Mills',
 'Banbury-Don Mills',
 'Victoria Village',
 'Flemingdon Park',
 'Pleasant View',
 'Don Valley Village',
 'Hillcrest Village',
 'Bayview Woods-Steeles',
 'Newtonbrook East',
 'Bayview Village',
 'Henry Farm',
 'O`Connor Parkview',
 'Thorncliffe Park',
 'Leaside-Bennington',
 'Broadview North',
 'Old East York',
 'Danforth-East York',
 'Woodbine-Lumsden',
 'Taylor Massey',
 'East End Danforth',
 'The Beaches',
 'Woodbine Corridor',
 'Greenwood-Coxwell',
 'Danforth',
 'Playter Estates-Danforth',
 'North Riverdale',
 'Blake-Jones',
 'South Riverdale',
 'Cabbagetown-South St. James Town',
 'Regent Park',
 'Moss Park',
 'North St. James Town',
 'Kensington-Chinatown',
 'University',
 'Palmerston-Little Italy',
 'Trinity-Bellwoods',
 'Dufferin Grove',
 'Little Portugal',
 'South Parkdale',
 'Roncesvalles',
 'High Park-Swansea',
 'High Park North',
 'Runnymede-Bloor West Village',
 'Junction Area',
 'Weston-Pelham Park',
 'Corso Italia-Davenport',
 'Wychwood',
 'Annex',
 'Casa Loma',
 'Yonge-St. Clair',
 'Rosedale-Moore Park',
 'Mount Pleasant East',
 'Yonge-Eglinton',
 'Forest Hill South',
 'Forest Hill North',
 'Lawrence Park South',
 'Lawrence Park North',
 'Humewood-Cedarvale',
 'Oakwood Village',
 'Briar Hill-Belgravia',
 'Caledonia-Fairbank',
 'Keelesdale-Eglinton West',
 'Rockcliffe-Smythe',
 'Beechborough-Greenbrook',
 'Weston',
 'Lambton Baby Point',
 'Mount Dennis',
 'Steeles',
 "Tam O'Shanter-Sullivan",
 'Wexford/Maryvale',
 'Clairlea-Birchmount',
 'Oakridge',
 'Birchcliffe-Cliffside',
 'Cliffcrest',
 'Kennedy Park',
 'Ionview',
 'Dorset Park',
 'Agincourt South-Malvern West',
 'Agincourt North',
 'Milliken',
 'Centennial Scarborough',
 'Highland Creek',
 'Morningside',
 'West Hill',
 'Eglinton East',
 'Scarborough Village',
 'Guildwood',
 'Golfdale-Cedarbrae-Woburn',
 'Woburn North',
 'West Rouge',
 'Morningside Heights',
 'Malvern West',
 'Malvern East',
 "L'Amoreaux West",
 "East L'Amoreaux",
 "Parkwoods-O'Connor Hills",
 'Fenside-Parkwoods',
 'Yonge-Doris',
 'East Willowdale',
 'Avondale',
 'Oakdale-Beverley Heights',
 'Downsview',
 'Bendale-Glen Andrew',
 'Bendale South',
 'Islington',
 'Etobicoke City Centre',
 'Mimico-Queensway',
 'Humber Bay Shores',
 'West Queen West',
 'Fort York-Liberty Village',
 'Wellington Place',
 'Harbourfront-CityPlace',
 'St Lawrence-East Bayfront-The Islands',
 'Church-Wellesley',
 'Downtown Yonge East',
 'Bay-Cloverhill',
 'Yonge-Bay Corridor',
 'Junction-Wallace Emerson',
 'Dovercourt Village',
 'North Toronto',
 'South Eglinton-Davisville']

In [6]:
child_centres["dropinHours"].unique()

array(['Wednesday: 9:00 a.m. - 11:30 a.m.  ', None,
       'Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.  ; 1:30 p.m. - 2:30 p.m.   | Tuesday: 9:00 a.m. - noon  ; 10:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:30 p.m.   | Wednesday: 9:00 a.m. - noon  ; 10:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:30 p.m.   | Thursday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.  ; 4:30 p.m. - 7:00 p.m.   | Friday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.   | Saturday: 9:30 a.m. - noon  ',
       'Monday: 10:00 a.m. - noon  ; 3:30 p.m. - 6:00 p.m.   | Tuesday: 2:00 p.m. - 4:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 2:00 p.m. - 4:00 p.m.   | Friday: 10:00 a.m. - noon   | Saturday: 10:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:30 p.m.   | Tuesday: 1:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - 11:30 a.m.   | Thursday: 1:00 p.m. - 3:30 p.m.   | Friday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:30 p.m.  ',
       'Wednesday: 1:00 p.m. - 3:30 p.m.  ',
       'Saturday: 9:00 a.m. - 11:00 a.m.  ',
       'Monday: 2:00 p.m. - 4:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.   | Friday: 10:00 a.m. - noon  ',
       'Monday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Tuesday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Wednesday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon   | Thursday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon   | Friday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Saturday: 9:00 a.m. - noon  ',
       'Monday: 1:00 p.m. - 4:00 p.m.   | Tuesday: 1:00 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - noon   | Friday: 10:00 a.m. - noon  ',
       'Monday: 5:00 p.m. - 7:00 p.m.   | Tuesday: 5:00 p.m. - 7:00 p.m.   | Saturday: 9:00 a.m. - 11:00 a.m.  ',
       'Monday: noon - 3:00 p.m.  ; 4:00 p.m. - 8:00 p.m.   | Tuesday: noon - 3:00 p.m.  ; 4:00 p.m. - 8:00 p.m.   | Wednesday: 9:30 a.m. - 3:00 p.m.  ; 4:00 p.m. - 8:00 p.m.  ; 9:30 a.m. - 3:00 p.m.  ; 4:00 p.m. - 8:00 p.m.   | Thursday: 9:30 a.m. - 12:30 p.m.  ; 1:30 p.m. - 5:30 p.m.  ; 9:30 a.m. - 12:30 p.m.  ; 1:30 p.m. - 5:30 p.m.   | Friday: 9:30 a.m. - 12:30 p.m.  ; 1:30 p.m. - 5:30 p.m.  ; 9:30 a.m. - 12:30 p.m.  ; 1:30 p.m. - 5:30 p.m.   | Saturday: 12:30 p.m. - 3:30 p.m.  ',
       'Tuesday: 3:30 p.m. - 5:00 p.m.   | Thursday: 9:30 a.m. - 11:00 a.m.  ',
       'Thursday: 4:00 p.m. - 5:15 p.m.  ',
       'Monday: 9:00 a.m. - 1:00 p.m.   | Tuesday: 9:00 a.m. - 1:00 p.m.   | Wednesday: 9:00 a.m. - 1:00 p.m.   | Thursday: 9:00 a.m. - 1:00 p.m.   | Friday: 9:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:30 a.m. - 2:30 p.m.  ; 9:30 a.m. - 6:00 p.m.   | Tuesday: 9:30 a.m. - 12:30 p.m.   | Wednesday: 9:30 a.m. - 2:30 p.m.   | Thursday: 9:30 a.m. - 12:30 p.m.   | Friday: 9:30 a.m. - 2:30 p.m.   | Saturday: 9:30 a.m. - 3:00 p.m.  ',
       'Monday: 10:00 a.m. - 1:00 p.m.   | Tuesday: 1:00 p.m. - 3:45 p.m.   | Thursday: 1:00 p.m. - 3:45 p.m.  ',
       'Wednesday: 9:30 a.m. - 1:00 p.m.   | Friday: 9:30 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - 2:00 p.m.   | Tuesday: 9:00 a.m. - 2:00 p.m.   | Wednesday: 9:00 a.m. - 2:00 p.m.   | Thursday: 9:00 a.m. - 2:00 p.m.  ',
       'Monday: 9:00 a.m. - 3:00 p.m.  ; 5:00 p.m. - 7:00 p.m.   | Tuesday: 1:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Thursday: 1:30 p.m. - 3:30 p.m.  ; 4:00 p.m. - 7:00 p.m.   | Friday: 9:00 a.m. - noon   | Saturday: 10:00 a.m. - 1:00 p.m.  ',
       'Monday: 12:30 p.m. - 4:15 p.m.   | Tuesday: 12:30 p.m. - 4:15 p.m.   | Wednesday: 12:30 p.m. - 4:15 p.m.   | Thursday: 12:30 p.m. - 4:15 p.m.   | Friday: 12:30 p.m. - 4:15 p.m.   | Saturday: 12:30 p.m. - 3:00 p.m.  ',
       'Monday: 8:45 a.m. - 12:30 p.m.   | Tuesday: 8:45 a.m. - 12:30 p.m.   | Wednesday: 8:45 a.m. - 12:30 p.m.   | Thursday: 8:45 a.m. - 12:30 p.m.   | Friday: 8:45 a.m. - 12:30 p.m.  ',
       'Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.   | Tuesday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.  ; 4:30 p.m. - 7:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.  ; 4:30 p.m. - 7:00 p.m.   | Thursday: 9:00 a.m. - noon  ; 4:30 p.m. - 7:00 p.m.   | Friday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.   | Saturday: 9:30 a.m. - 12:30 p.m.  ',
       'Tuesday: 1:30 p.m. - 3:00 p.m.  ',
       'Monday: 9:15 a.m. - 2:15 p.m.   | Tuesday: 9:15 a.m. - 2:15 p.m.   | Wednesday: 9:15 a.m. - 2:15 p.m.   | Thursday: 9:15 a.m. - 2:15 p.m.  ',
       'Monday: 9:00 a.m. - 11:30 a.m.   | Tuesday: 9:00 a.m. - 11:30 a.m.   | Wednesday: 1:30 p.m. - 6:00 p.m.   | Thursday: 9:00 a.m. - 11:30 a.m.  ; 1:30 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - 11:30 a.m.  ',
       'Tuesday: 10:00 a.m. - 1:00 p.m.   | Thursday: 10:00 a.m. - 1:00 p.m.   | Saturday: 10:00 a.m. - 1:00 p.m.  ',
       'Monday: 8:45 a.m. - 1:45 p.m.   | Tuesday: 8:45 a.m. - 1:45 p.m.   | Wednesday: 8:45 a.m. - 1:45 p.m.   | Thursday: 8:45 a.m. - 1:45 p.m.  ',
       'Monday: 9:00 a.m. - 1:00 p.m.   | Tuesday: 9:00 a.m. - 1:00 p.m.   | Wednesday: 9:00 a.m. - 1:00 p.m.  ; 4:00 p.m. - 6:00 p.m.   | Thursday: 9:00 a.m. - 1:00 p.m.   | Friday: 9:00 a.m. - 1:00 p.m.   | Saturday: 9:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.   | Tuesday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.  ',
       'Monday: 10:00 a.m. - 2:00 p.m.   | Tuesday: 10:00 a.m. - 2:00 p.m.   | Wednesday: 10:00 a.m. - 2:00 p.m.   | Thursday: 10:00 a.m. - 2:00 p.m.   | Friday: 10:00 a.m. - 2:00 p.m.  ',
       'Monday: 8:30 a.m. - 1:30 p.m.   | Tuesday: 8:30 a.m. - 1:30 p.m.   | Wednesday: 8:30 a.m. - 1:30 p.m.   | Thursday: 8:30 a.m. - 1:30 p.m.  ',
       'Monday: 8:45 a.m. - 12:45 p.m.   | Tuesday: 8:45 a.m. - 12:45 p.m.   | Wednesday: 8:45 a.m. - 12:45 p.m.   | Thursday: 8:45 a.m. - 12:45 p.m.   | Friday: 8:45 a.m. - 12:45 p.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Tuesday: 9:30 a.m. - noon   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 4:00 p.m.   | Thursday: 10:00 a.m. - noon   | Saturday: 9:30 a.m. - 11:00 a.m.  ; 11:00 a.m. - 12:30 p.m.  ',
       'Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.  ; noon - 6:00 p.m.   | Thursday: 9:00 a.m. - 3:00 p.m.   | Friday: 9:00 a.m. - 1:00 p.m.   | Saturday: 10:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 11:30 a.m.   | Thursday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Friday: 10:00 a.m. - 11:30 a.m.  ',
       'Monday: 9:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Tuesday: 2:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - noon   | Thursday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 2:30 p.m.   | Friday: 9:00 a.m. - 2:30 p.m.   | Saturday: 10:00 a.m. - 2:00 p.m.  ',
       'Monday: 8:00 a.m. - noon   | Tuesday: 8:00 a.m. - noon   | Wednesday: 8:00 a.m. - noon   | Thursday: 8:00 a.m. - noon   | Friday: 8:00 a.m. - noon  ',
       'Monday: 2:00 p.m. - 4:00 p.m.   | Tuesday: 9:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 3:00 p.m. - 4:00 p.m.   | Thursday: 2:00 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - noon   | Saturday: 10:00 a.m. - noon  ',
       'Tuesday: 9:30 a.m. - 3:00 p.m.   | Wednesday: 10:00 a.m. - 11:30 a.m.   | Thursday: 9:30 a.m. - 3:00 p.m.   | Friday: 9:30 a.m. - noon   | Saturday: 9:30 a.m. - noon  ',
       'Tuesday: 9:00 a.m. - noon   | Wednesday: 10:00 a.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 1:00 p.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 2:30 p.m.   | Wednesday: 9:00 a.m. - noon   | Saturday: 9:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 11:00 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.  ',
       'Tuesday: 9:30 a.m. - 11:00 a.m.  ',
       'Tuesday: 12:15 p.m. - 3:15 p.m.   | Wednesday: 8:30 a.m. - 11:30 a.m.  ; 12:15 p.m. - 3:15 p.m.  ; 9:00 a.m. - noon  ; 12:30 p.m. - 3:30 p.m.   | Thursday: 12:15 p.m. - 3:15 p.m.  ; 12:30 p.m. - 3:30 p.m.  ',
       'Monday: 10:30 a.m. - noon   | Wednesday: 10:30 a.m. - 12:30 p.m.  ',
       'Monday: 8:15 a.m. - 1:15 p.m.   | Tuesday: 8:15 a.m. - 1:15 p.m.   | Wednesday: 8:15 a.m. - 1:15 p.m.   | Thursday: 8:15 a.m. - 1:15 p.m.  ',
       'Monday: 8:30 a.m. - 12:30 p.m.   | Tuesday: 8:30 a.m. - 12:30 p.m.   | Wednesday: 8:30 a.m. - 12:30 p.m.   | Thursday: 8:30 a.m. - 12:30 p.m.   | Friday: 8:30 a.m. - 12:30 p.m.  ',
       'Sunday: 1:00 p.m. - 4:00 p.m.   | Monday: 9:30 a.m. - 1:00 p.m.   | Tuesday: 9:30 a.m. - 1:00 p.m.   | Wednesday: 9:30 a.m. - 3:00 p.m.   | Thursday: 9:30 a.m. - 1:00 p.m.   | Friday: 9:30 a.m. - 1:00 p.m.  ',
       'Monday: 10:30 a.m. - 4:00 p.m.   | Tuesday: 9:00 a.m. - 10:15 a.m.  ; 11:15 a.m. - 1:00 p.m.  ; 3:00 p.m. - 3:30 p.m.   | Wednesday: 10:00 a.m. - 10:30 a.m.  ; 11:00 a.m. - 11:30 a.m.  ; 12:30 p.m. - 2:00 p.m.  ; 3:00 p.m. - 5:00 p.m.   | Thursday: 10:00 a.m. - 1:00 p.m.  ; 3:00 p.m. - 5:00 p.m.   | Friday: 10:00 a.m. - 11:00 a.m.  ; noon - 3:00 p.m.  ; 4:00 p.m. - 5:00 p.m.   | Saturday: 3:00 p.m. - 3:30 p.m.  ; 4:00 p.m. - 5:00 p.m.  ',
       'Wednesday: 10:00 a.m. - 11:30 a.m.   | Friday: 10:00 a.m. - 11:30 a.m.  ',
       'Monday: 9:00 a.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 3:00 p.m.   | Friday: 9:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Friday: 9:00 a.m. - 11:30 a.m.   | Saturday: 10:00 a.m. - noon  ; 12:30 p.m. - 2:00 p.m.  ',
       'Monday: 9:00 a.m. - noon   | Tuesday: 1:00 p.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 11:00 a.m.   | Tuesday: 10:30 a.m. - 11:30 a.m.   | Wednesday: 9:00 a.m. - 10:00 a.m.  ; 9:00 a.m. - 11:00 a.m.   | Thursday: 10:00 a.m. - 11:00 a.m.  ; 10:30 a.m. - 11:30 a.m.  ; 10:00 a.m. - 11:00 a.m.   | Friday: 9:00 a.m. - 11:00 a.m.  ',
       'Monday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.  ; 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Tuesday: 1:00 p.m. - 3:00 p.m.  ; 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Wednesday: 1:00 p.m. - 3:00 p.m.  ; 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 11:30 a.m.   | Friday: 1:00 p.m. - 3:00 p.m.  ; 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Saturday: 9:00 a.m. - 2:00 p.m.  ',
       'Tuesday: 9:30 a.m. - 11:30 a.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ',
       'Wednesday: 10:30 a.m. - 11:30 a.m.  ',
       'Wednesday: 10:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 3:00 p.m.   | Friday: 9:00 a.m. - 3:00 p.m.  ',
       'Tuesday: 10:30 a.m. - 11:30 a.m.  ; 1:00 p.m. - 2:00 p.m.  ',
       'Monday: 9:15 a.m. - 1:15 p.m.   | Tuesday: 9:15 a.m. - 1:15 p.m.   | Wednesday: 9:15 a.m. - 1:15 p.m.   | Thursday: 9:15 a.m. - 1:15 p.m.   | Friday: 9:15 a.m. - 1:15 p.m.  ',
       'Monday: 9:00 a.m. - 1:30 p.m.   | Tuesday: 9:00 a.m. - 1:30 p.m.   | Wednesday: 9:00 a.m. - noon  ; 12:30 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - 1:30 p.m.  ',
       'Monday: 9:00 a.m. - 7:00 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Friday: 9:00 a.m. - 3:00 p.m.   | Saturday: 9:00 a.m. - noon  ',
       'Monday: 9:15 a.m. - noon  ; noon - 3:00 p.m.   | Tuesday: 9:15 a.m. - noon  ; noon - 3:00 p.m.  ; 1:00 p.m. - 3:00 p.m.  ; 3:00 p.m. - 7:00 p.m.   | Wednesday: 9:15 a.m. - noon  ; noon - 4:30 p.m.   | Thursday: 9:15 a.m. - noon  ; noon - 3:00 p.m.   | Friday: 9:30 a.m. - 3:30 p.m.  ',
       'Monday: 10:00 a.m. - 11:30 a.m.   | Tuesday: 10:00 a.m. - noon  ; 3:30 p.m. - 6:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 2:00 p.m. - 3:30 p.m.  ; 4:30 p.m. - 6:30 p.m.   | Saturday: 9:00 a.m. - noon  ',
       'Friday: 9:30 a.m. - 11:30 a.m.  ',
       'Monday: 9:00 a.m. - noon   | Tuesday: 9:00 a.m. - noon   | Wednesday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 1:00 p.m. - 2:45 p.m.   | Thursday: 1:00 p.m. - 2:45 p.m.  ',
       'Tuesday: 9:00 a.m. - noon  ; 4:00 p.m. - 6:00 p.m.   | Wednesday: 9:00 a.m. - noon   | Thursday: 9:00 a.m. - noon  ; 1:30 p.m. - 3:30 p.m.   | Saturday: 9:30 a.m. - noon  ',
       'Monday: 9:00 a.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - noon   | Wednesday: 9:00 a.m. - noon  ; 5:00 p.m. - 7:00 p.m.   | Saturday: 9:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - 2:30 p.m.  ',
       'Tuesday: 9:00 a.m. - noon   | Wednesday: 9:00 a.m. - noon   | Thursday: 9:00 a.m. - noon  ',
       'Monday: 3:30 p.m. - 5:00 p.m.  ',
       'Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.  ; 5:00 p.m. - 7:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 2:00 p.m.  ; 2:30 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - noon   | Saturday: 9:30 a.m. - 11:30 a.m.  ',
       'Sunday: 9:30 a.m. - 11:30 a.m.   | Monday: 9:30 a.m. - 11:30 a.m.   | Tuesday: 9:30 a.m. - 11:00 a.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 6:00 p.m. - 7:30 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ',
       'Friday: 9:30 a.m. - 11:00 a.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 6:00 p.m. - 7:30 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 3:30 p.m. - 5:00 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 6:00 p.m. - 7:30 p.m.   | Saturday: 9:30 a.m. - 11:30 a.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.   | Tuesday: 1:30 p.m. - 3:30 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 4:30 p.m. - 6:30 p.m.  ; 9:30 a.m. - 11:30 a.m.   | Thursday: 9:30 a.m. - 11:30 a.m.   | Friday: 1:30 p.m. - 3:30 p.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.   | Thursday: 1:30 p.m. - 3:00 p.m.  ',
       'Thursday: 10:30 a.m. - 12:30 p.m.  ',
       'Monday: 2:00 p.m. - 6:00 p.m.   | Tuesday: noon - 4:00 p.m.   | Wednesday: noon - 4:00 p.m.   | Thursday: noon - 4:00 p.m.   | Friday: noon - 3:00 p.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 4:00 p.m. - 5:00 p.m.   | Tuesday: 9:30 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Thursday: 9:30 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Friday: 9:30 a.m. - 11:30 a.m.  ',
       'Sunday: 1:30 p.m. - 6:30 p.m.   | Monday: 9:00 a.m. - 12:30 p.m.   | Tuesday: 9:00 a.m. - 12:30 p.m.   | Wednesday: 9:00 a.m. - 12:30 p.m.   | Thursday: 1:30 p.m. - 4:30 p.m.   | Friday: 9:00 a.m. - 12:30 p.m.   | Saturday: 9:30 a.m. - noon  ',
       'Thursday: 9:30 a.m. - 11:30 a.m.   | Friday: 9:00 a.m. - 11:30 a.m.  ',
       'Monday: 9:00 a.m. - noon  ; 2:30 p.m. - 4:00 p.m.   | Tuesday: 9:00 a.m. - noon  ; 1:30 p.m. - 3:00 p.m.  ; 3:30 p.m. - 5:30 p.m.   | Wednesday: 9:00 a.m. - noon  ; 1:30 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - noon  ; 1:30 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - noon  ; 2:30 p.m. - 4:00 p.m.   | Saturday: 9:00 a.m. - 11:30 a.m.  ',
       'Saturday: 9:45 a.m. - 12:30 p.m.  ',
       'Monday: 10:30 a.m. - 1:00 p.m.   | Thursday: 2:00 p.m. - 4:30 p.m.  ',
       'Monday: 4:30 p.m. - 7:30 p.m.   | Tuesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Friday: 10:00 a.m. - noon  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 10:30 a.m. - 11:30 a.m.   | Tuesday: 9:30 a.m. - 10:30 a.m.  ; 10:30 a.m. - 11:30 a.m.  ; 2:00 p.m. - 4:00 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ; 4:30 p.m. - 5:30 p.m.   | Friday: 9:30 a.m. - 11:30 a.m.  ; 10:30 a.m. - 11:30 a.m.   | Saturday: 10:00 a.m. - noon  ',
       'Monday: 7:45 a.m. - 11:45 a.m.   | Tuesday: 7:45 a.m. - 11:45 a.m.   | Wednesday: 7:45 a.m. - 11:45 a.m.   | Thursday: 7:45 a.m. - 11:45 a.m.   | Friday: 7:45 a.m. - 11:45 a.m.  ',
       'Monday: 9:00 a.m. - 12:30 p.m.   | Tuesday: 9:00 a.m. - 12:30 p.m.   | Wednesday: 9:00 a.m. - 12:30 p.m.  ; 3:30 p.m. - 4:30 p.m.   | Thursday: 9:00 a.m. - 12:30 p.m.   | Friday: 9:00 a.m. - 12:30 p.m.  ',
       'Monday: 9:00 a.m. - 11:30 a.m.   | Tuesday: 9:00 a.m. - 11:30 a.m.   | Thursday: 9:00 a.m. - 11:30 a.m.   | Friday: 9:30 a.m. - 11:30 a.m.  ',
       'Thursday: 9:30 a.m. - 11:30 a.m.  ',
       'Monday: 10:30 a.m. - 11:30 a.m.  ',
       'Tuesday: 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 5:00 p.m. - 6:30 p.m.   | Wednesday: 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.   | Thursday: 8:30 a.m. - 11:30 a.m.   | Friday: 1:30 p.m. - 3:30 p.m.  ; 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Saturday: 1:30 p.m. - 3:30 p.m.  ',
       'Monday: 8:15 a.m. - 12:15 p.m.   | Tuesday: 8:15 a.m. - 12:15 p.m.   | Wednesday: 8:15 a.m. - 12:15 p.m.   | Thursday: 8:15 a.m. - 12:15 p.m.   | Friday: 8:15 a.m. - 12:15 p.m.  ',
       'Monday: 9:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Tuesday: 2:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 8:30 a.m. - 4:15 p.m.   | Tuesday: 8:45 a.m. - 6:00 p.m.   | Wednesday: 8:45 a.m. - 6:00 p.m.   | Thursday: 8:45 a.m. - 4:15 p.m.   | Friday: 8:45 a.m. - 4:15 p.m.  ',
       'Monday: 9:00 a.m. - 1:00 p.m.  ; 2:30 p.m. - 6:00 p.m.   | Tuesday: 9:00 a.m. - 1:00 p.m.  ; 2:30 p.m. - 6:00 p.m.   | Wednesday: 9:00 a.m. - 1:00 p.m.  ; 2:30 p.m. - 6:00 p.m.   | Thursday: 9:00 a.m. - 1:00 p.m.  ; 2:30 p.m. - 6:00 p.m.   | Friday: 9:00 a.m. - 1:00 p.m.   | Saturday: 9:00 a.m. - 11:00 a.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Friday: 9:30 a.m. - 11:30 a.m.   | Saturday: 9:30 a.m. - noon  ; 12:30 p.m. - 2:00 p.m.  ',
       'Tuesday: 9:30 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Wednesday: 11:30 a.m. - 3:00 p.m.   | Thursday: 9:30 a.m. - 10:30 a.m.  ; 11:30 a.m. - 1:00 p.m.   | Friday: 4:00 p.m. - 6:00 p.m.  ',
       'Monday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Tuesday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Thursday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Friday: 10:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - noon   | Wednesday: 1:30 p.m. - 3:30 p.m.   | Thursday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 9:30 a.m. - noon  ; 1:00 p.m. - 3:00 p.m.   | Tuesday: 1:00 p.m. - 3:00 p.m.   | Wednesday: 9:30 a.m. - noon   | Thursday: 9:30 a.m. - noon  ; 1:00 p.m. - 2:30 p.m.  ; 4:00 p.m. - 6:30 p.m.   | Friday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.  ',
       'Monday: 9:00 a.m. - 1:30 p.m.   | Tuesday: 1:00 p.m. - 5:30 p.m.   | Thursday: 9:00 a.m. - 1:30 p.m.   | Friday: 9:00 a.m. - 1:30 p.m.   | Saturday: 9:30 a.m. - 12:30 p.m.  ',

In [7]:
def categorize_hours(text):
    if pd.isna(text) or not isinstance(text, str) or text.strip() == "":
        return "Other"
    
    t = text.lower()
    
    # Detect days
    days = re.findall(r"(monday|tuesday|wednesday|thursday|friday|saturday|sunday)", t)
    unique_days = set(days)
    
    # Detect if weekend present
    weekend = bool({"saturday", "sunday"} & unique_days)
    
    # Detect time ranges
    evening = bool(re.search(r"(5|6|7|8|9):\d{0,2}\s*p\.?m\.?", t))
    morning = bool(re.search(r"(7|8|9|10|11):\d{0,2}\s*a\.?m\.?", t))
    afternoon = bool(re.search(r"(12|1|2|3|4):\d{0,2}\s*p\.?m\.?", t))
    
    # Apply logic
    if weekend:
        return "Weekend available"
    elif evening:
        return "Evening available"
    elif morning and afternoon:
        return "Full day"
    elif morning:
        return "Morning only"
    elif afternoon:
        return "Afternoon only"
    else:
        return "Other"

child_centres["hourCategory"] = child_centres["dropinHours"].apply(categorize_hours)

child_centres["hourCategory"]

0           Morning only
1                  Other
2      Weekend available
3      Weekend available
4               Full day
             ...
225    Weekend available
226    Weekend available
227                Other
228             Full day
229    Evening available
Name: hourCategory, Length: 230, dtype: object

In [ ]:
child_centres['address']

Index(['_id', 'service_system_manager', 'agency', 'loc_id', 'program_name',
       'languages', 'french_language_program', 'indigenous_program',
       'programTypes', 'serviceName', 'buildingName', 'address',
       'full_address', 'major_intersection', 'ward', 'ward_name',
       'located_in_school', 'school_name', 'lat', 'lng', 'website',
       'website_name', 'website_description', 'consultant_fullname',
       'consultant_phone', 'email', 'contact_fullname', 'contact_title',
       'phone', 'contact_email', 'dropinHours', 'registeredHours',
       'virtualHours', 'centre_type', 'geometry', 'hourCategory'],
      dtype='object')

In [11]:
child_centres.to_file('/Users/lucasben/Documents/mba-business-analytics/Data Viz Data Folder/child_centres_clean.geojson', driver="GeoJSON")

In [16]:
# In 2022, Toronto designated 33 neighbourhoods as vulnerable areas compared to 14 in 2014.

(33 - 14) / 14 * 100

135.71428571428572

In [39]:
list(improvement_areas.columns)

['_id',
 'AREA_ID',
 'DATE_EFFECTIVE',
 'DATE_EXPIRY',
 'AREA_ATTR_ID',
 'AREA_TYPE_ID',
 'PARENT_AREA_ID',
 'AREA_TYPE',
 'AREA_CLASS_ID',
 'AREA_CLASS',
 'AREA_SHORT_CODE',
 'AREA_LONG_CODE',
 'AREA_NAME',
 'AREA_DESC',
 'FEATURE_CODE',
 'FEATURE_CODE_DESC',
 'TRANS_ID_CREATE',
 'TRANS_ID_EXPIRE',
 'OBJECTID',
 'geometry']

In [40]:
list(neighbourhoods.columns)

['_id',
 'AREA_ID',
 'AREA_ATTR_ID',
 'PARENT_AREA_ID',
 'AREA_SHORT_CODE',
 'AREA_LONG_CODE',
 'AREA_NAME',
 'AREA_DESC',
 'CLASSIFICATION',
 'CLASSIFICATION_CODE',
 'OBJECTID',
 'geometry']

In [47]:
matching_values = transpose['Neighbourhood'].isin(neighbourhoods['AREA_NAME'])

In [56]:
missing = neighbourhoods[~neighbourhoods['AREA_NAME'].isin(transpose['Neighbourhood'])]
print(missing['AREA_NAME'])

60                      Yonge-St.Clair
81                 North St.James Town
84     Cabbagetown-South St.James Town
93                   East End-Danforth
94                       Taylor-Massey
96                  Danforth East York
130                  O'Connor-Parkview
Name: AREA_NAME, dtype: object

In [52]:
matching_values2 = transpose['Neighbourhood'].isin(improvement_areas['AREA_NAME'])
count_true = matching_values2.sum()
print(count_true)

32

In [53]:
len(improvement_areas)

33

In [54]:
missing_from_transpose = improvement_areas[~improvement_areas['AREA_NAME'].isin(transpose['Neighbourhood'])]
print(missing_from_transpose)

    _id    AREA_ID      DATE_EFFECTIVE          DATE_EXPIRY  AREA_ATTR_ID  \
18   19  2502272.0 2022-04-11 21:27:23  3000/01/01 05:00:00    26022787.0

    AREA_TYPE_ID PARENT_AREA_ID AREA_TYPE AREA_CLASS_ID AREA_CLASS  \
18         602.0           None      CNBH          None       None

   AREA_SHORT_CODE AREA_LONG_CODE      AREA_NAME           AREA_DESC  \
18             061            061  Taylor-Massey  Taylor-Massey (61)

   FEATURE_CODE FEATURE_CODE_DESC  TRANS_ID_CREATE  TRANS_ID_EXPIRE  OBJECTID  \
18         None              None         344709.0             -1.0  17826241

                                             geometry
18  MULTIPOLYGON (((-79.29348 43.70302, -79.29314 ...

## **Preprocessing**

In [ ]:
neighbourhood_metrics = pd.DataFrame()

neighbourhood_metrics['neighbourhood_name'] = transpose['Neighbourhood']
neighbourhood_metrics['children_0_4'] = transpose['']


neighbourhood_metrics = {
    'neighbourhood_id': [],
    'neighbourhood_name': [], 
    'is_nia': [],  
    'children_0_4': [],
    'single_mother_families': [],
    'median_household_income': [],
    'gini_index': [],
    'pct_low_income': [],  # bottom half of income distribution
    'childcare_centres_count': [],
    'childcare_capacity_per_child': [],  # centres per 100 children
    'income_decile': []  # 1-10 scale
}

childcare_centres = {
    'centre_id': [],
    'centre_name': [],
    'neighbourhood_id': [],  # key for joining later
    'address': [],
    'geometry': []
    'hourCategory': []
}

In [ ]:
neighbourhood_metrics = pd.DataFrame()

neighbourhood_metrics['neighbourhood_name'] = transpose['Neighbourhood']
neighbourhood_metrics['children_0_4'] = transpose['    0 to 4 years'] # childcare centers are for infants to preschool
neighbourhood_metrics['median_age_population'] = transpose['Median age of the population']
neighbourhood_metrics['median_after_tax_income_2020_over_15'] = transpose[ '    Median after-tax income in 2020 among recipients ($)']
neighbourhood_metrics['after_tax_bottom_half_distribution'] = transpose['  In bottom half of the distribution']
neighbourhood_metrics[ '    In bottom decile'] = transpose['    In bottom decile']
neighbourhood_metrics[ '    In second decile'] = transpose['    In second decile']
neighbourhood_metrics[ '    In third decile'] = transpose['    In third decile']
neighbourhood_metrics[ '    In fourth decile'] = transpose['    In fourth decile']
neighbourhood_metrics[ '    In fifth decile'] = transpose['    In fifth decile']
neighbourhood_metrics[ '    In sixth decile'] = transpose['    In sixth decile']
neighbourhood_metrics[ '    In seventh decile'] = transpose['    In seventh decile']
neighbourhood_metrics[ '    In eighth decile'] = transpose['    In eighth decile']
neighbourhood_metrics[ '    In ninth decile'] = transpose['    In ninth decile']
neighbourhood_metrics[ '    In top decile'] = transpose['    In top decile']
neighbourhood_metrics['inequality_index'] = transpose['  Gini index on adjusted household after-tax income']

with_children_cols = transpose.filter(like='With children')
transpose['count_of_children'] = with_children_cols.sum(axis=1) # row wise sum
neighbourhood_metrics['count_of_children'] = transpose['count_of_children']

neighbourhood_metrics['single_moms'] = transpose[ '    in which the parent is a woman+']

In [65]:
neighbourhood_metrics

,neighbourhood_name,children_0_4,median_age_population,median_after_tax_income_2020_over_15,after_tax_bottom_half_distribution,In bottom decile,In second decile,In third decile,In fourth decile,In fifth decile,In sixth decile,In seventh decile,In eighth decile,In ninth decile,In top decile,inequality_index,count_of_children,single_moms
0,West Humber-Clairville,1460,38,31600,17320,3430,3460,3270,3585,3580,3850,3725,3485,3300,1610,0.2,7090,1695
1,Mount Olive-Silverstone-Jamestown,1650,36,28400,21365,4465,4885,4645,3915,3460,3505,2635,2155,1240,455,0.2,6830,2060
2,Thistletown-Beaumond Heights,505,39.2,30600,5790,1215,1030,1160,1240,1145,985,905,845,735,595,0.3,2110,540
3,Rexdale-Kipling,505,42,31800,5795,1390,1155,1225,1105,925,1155,925,1010,1035,460,0.3,2220,630
4,Elms-Old Rexdale,440,38.4,32400,5150,1075,1045,1250,1030,750,955,1365,740,740,405,0.3,1735,740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Yonge-Bay Corridor,500,31,40400,6880,2985,1420,1030,765,670,845,840,965,1195,1920,0.4,1370,335
154,Junction-Wallace Emerson,1135,37.6,37200,11315,2595,2250,2080,2205,2185,2255,1990,2480,2365,2775,0.3,4725,940
155,Dovercourt Village,445,39.2,34800,6000,1435,1360,1300,750,1155,1060,1000,1125,1225,1970,0.3,2335,475
156,North Toronto,535,35.2,41200,8480,2630,1595,1555,1240,1465,1540,1570,1525,1340,1430,0.3,2005,570
157,South Eglinton-Davisville,910,36,46000,10335,3305,1725,1745,1640,1925,2010,1995,2215,2635,3550,0.4,3220,720